### ISSUE TITLE
Sampling from a mixture distribution

### ISSUE THREAD

**Issue by RaphaelS1** [alan-turing-institute/distr6#100]
Let M1 and M2 be models in a mixture distribution with respective weights W1 and W2 and sampling methods S1 and S2. Is it correct that sampling from the mixture distribution is done by first randomly selecting one of the models M1 and M2 using the weights and then sampling from that distribution? e.g. in R pseudo-code
````R
m <- MixtureDistribution$new(M1,M2)
m$rand <- function(n){
 models <- sample(c(M1,M2), weights = c(W1, W2))
 models$rand(n)
}
````

**Comment by RaphaelS1** [comment]
Similar question about sampling from product/array distributions

**Comment by fkiraly** [comment]
Statement about mixtures is correct: select a component from a discrete with respective weights, then sample from that.

This is not the same for products/arrays. There, you simply sample from *all* components, and put them in the product/array.

**Comment by RaphaelS1** [comment]
Okay this is what I've done.

Does ordering matter for mixtures?
For example, say we map M1 and M2 to numerics "1,2" and run `sample(c(1,2), weights = c(0.1,0.9))` and output is `1,2,2,2,1,2,1,2,2,2` do we have to return the respective draws from M1 and M2 in this order? Or, can we be more efficient instead return 3 draws from M1 and then 7 draws from M2 (and if needs be randomly shuffle these after)?

**Comment by fkiraly** [comment]
That almost works, as follows:
1. sample the number of samples coming from a component from a multinomial
2. draw the respective number of samples from the component, in order
3. randomly permute the sample

**Comment by RaphaelS1** [comment]
Sorry I'm still confused how that differs from `sample(c(1,2), size = 10, replace = T, weights = c(0.1,0.9))`

**Comment by fkiraly** [comment]
Well, the difference is between sampling the *counts* (of successes/failurs) vs sampling the *trials*.

That is between
`table(sample(c(1,2), size = 10, replace = T)`
and
`sample(c(1,2), size = 10, replace = T)`
where the first can be done more efficiently than running `sample` (of trials) then `table`, namely by directly sampling from a binomial, or multinomial.

**Comment by RaphaelS1** [comment]
Aha! So sampling 10 points from the mixture of Binomial, Exponential, Normal with weights c(0.1,0.2,0.7) is equiv. to multinom$rand(10, probs = c(0.1,0.2,0.7))... although what's the `size` parameter in multinom?

**Comment by fkiraly** [comment]
Not exactly, the following are the same:
(a) sample N points from the mixture of k components with weights w_1, ..., w_k
(b) 
First: sample counts N_1, ..., N_k (size = N) from the multinomial, with component probabilities w_1, ..., w_k
Second: sample an i.i.d. sample of size N_1 from component 1, an i.i.d. sample of size N_2 from component 2, etc
Third: pool the samples and permute randomly

Exercise: prove that my claimed statement is correct (I hope there's no mistake in it)

**Comment by RaphaelS1** [comment]
Got it, the part that was confusing me was conflating 'number of draws from multinomial' the 'size' argument in 'sample' and 'number of trials'. The above follows from drawing one random sample from the Multinomial distribution with probabilities w_1,..,w_; this sample will give a table with K columns corresponding to each component and the values are number of samples to draws.

**Comment by RaphaelS1** [comment]
To confirm this is the code for mixture:

```R
  rand <- function(n){
    x = Multinomial$new(probs = private$.weights, size = n)$rand(1)
    y = c()
    for(i in 1:length(x))
      y = c(y, self$wrappedModels()[[i]]$rand(x[[i]]))
    return(sample(y, n))
  }
````

where `private$.weights` is the vector of weights and `self$wrappedModels()` calls the internal models

**Comment by fkiraly** [comment]
Yes, looks correct to me.
