### ISSUE TITLE
Automatic Numeric to Integer Conversion

### ISSUE THREAD

**Issue by RaphaelS1** [alan-turing-institute/distr6#103]
How do we want a discrete distribution to act when a float/non-integer is passed to it? Should we automatically convert to integer? And if so either by truncating (which occurs when using `as.integer`) e.g. `x$pdf(1.1) = x$pdf(1)` or rounding? The R stats default is to throw an error but I'm not convinced this is correct. However automatic conversion could cause problems with modelling down the line

**Comment by RaphaelS1** [comment]
In line with the distr6 philosophy that less errors is better, I'm opting for rounding

**Comment by fkiraly** [comment]
I think rounding to the next integer is problematic, as in distributions with support on the integer rounding up would increase value of the cdf.

I'd throw an error if the function expects integers, whereas if it is merely the support (of a real distribution) that is on the integers, floats are fine, and should return the appropriate cdf etc value.

**Comment by RaphaelS1** [comment]
> I think rounding to the next integer is problematic, as in distributions with support on the integer rounding up would increase value of the cdf.

And likewise rounding down would decrease the value of the cdf. Alternatively it could produce `0` which is what R stats does. My thinking is that if (later on) we use numeric integration as an approximation to (discrete) infinite sums, then throwing an error will disrupt the whole calculation.

**Comment by fkiraly** [comment]
Hm, I'm not sure whether I understand then.
Could you outline the exact case in which rounding would occur?
E.g., type of distribution, traits, support, user input, user input expected, desired behaviour (or options)?

**Comment by RaphaelS1** [comment]
Use-case: Binomial$new()$pdf(1.8)

This leads to one of:

* Error
* `return(0)`
* `return(Binomial$new()$pdf(1))` - Truncation
* `return(Binomial$new()$pdf(2))` - Rounding

**Comment by fkiraly** [comment]
Waitasecond - binomial distributions don't have a pdf (because they are not absolutely continuous with respect to the Lebesgue measure on the reals).

They have:
(a) a pmf when interpreted as a distribution over the integers, and 
(b) a cdf when interpreted as a distribution over the reals.

These may be considered as two cases, depending on what you see as the "support".

The "natural" thing would be, depending on what you interpret it as:
in case (a): throw an error, saying "argument should be an integer since this is a distribution over the integers"
in case (b): `return(BinomialOverIntegers$new()$cdf(floor(x)))`, since that's how the cdf is defined.

**Comment by fkiraly** [comment]
Though one may take a pragmatic stance and say that there's "only one" binomial distribution, and that has pmf, behaving as in case (a), as well as cdf, behaving as in case (b).

Alternatively, pmf just returns "0" for non-integers, following the convention that "pmf(x)" should be the same as "P(X=x)" for mixed distributions.

**Comment by RaphaelS1** [comment]
> Waitasecond - binomial distributions don't have a pdf (because they are not absolutely continuous with respect to the Lebesgue measure on the reals).

distr6 uses the Julia convention of referring to both pdfs and pmfs as densities (or pdfs)

> Alternatively, pmf just returns "0" for non-integers, following the convention that "pmf(x)" should be the same as "P(X=x)" for mixed distributions.

This was my thinking, whereas the R stats convention of throwing an error could be problematic
