### ISSUE TITLE
Multivariate Variance

### ISSUE THREAD

**Issue by RaphaelS1** [alan-turing-institute/distr6#104]
I've seen conflicting advice online for what to return for the variance of the distribution, I had initially implemented `var = diag(cov)` but on the wiki page for the multivariate normal it lists `var = cov` . Is there a standard?

**Comment by fkiraly** [comment]
I think the "general" thing is `var = cov`. For multivariate normal, all off-diagonals are zero, so in terms of information it is the same thing to return `diag(cov)`, but that's not output type consistent.
