### ISSUE TITLE
Change 'settable' to 'constructed' ?

### ISSUE THREAD

**Issue by RaphaelS1** [alan-turing-institute/distr6#115]
I think that the term 'settable' is too confusing as it contradicts the `setParameterValue` function and most users won't care about automated setting of parameters (which is when this does matter). Hence I think we should change this term to something like "constructed" or "reference". Although "reference" could be confusing as it does not necessarily refer to the actual reference/default parameter used by `updateFunc`

**Comment by fkiraly** [comment]
"mutable"? "tunable" (like in mlr2)? "interfaceable"?

**Comment by RaphaelS1** [comment]
Could this be later confused with 'fittable' though?

**Comment by fkiraly** [comment]
Perhaps worthwhile comparing how `paradox` solves this?

**Comment by RaphaelS1** [comment]
Agreed my plan is to shelve this until after discussions with the `paradox` team

**Comment by RaphaelS1** [comment]
Given talks today I think the simplest solution that doesn't screw up the whole API and will fit in with any future developments is to not re-name `settable` but instead to simply hide this column and have it be used internally only
