### ISSUE TITLE
Remove distrDomain?

### ISSUE THREAD

**Issue by RaphaelS1** [alan-turing-institute/distr6#116]
We have no real use for the `distrDomain` property at the moment and its presence could confuse users. I believe I'm correct in thinking that `distrDomain` will be useful with a modelling and `ProbFamily` interface but that this should be abstracted from core distributions

**Comment by fkiraly** [comment]
In the design, how is it different from `support`?

**Comment by RaphaelS1** [comment]
Support is exclusively used in pdf/cdf etc., `distrDomain` isn't queried at all internally. It just defaults to the same value as `type`. To me it doesn't seem to have any role in this version of distr6.

**Comment by RaphaelS1** [comment]
Of course we don't have to get rid of it if better documentation efficiently describes the future (or current) purpose of it

**Comment by fkiraly** [comment]
Confused - would you mind briefly summarizing how the discussion in #11 maps on current default interface points?

**Comment by RaphaelS1** [comment]
Quoting the initial question:

> Have we decided how, or whether, to specify the domain in which the random variable can take values?
This may make sense in multiple ways:
(i) the set where the r.v. with the given parameters may take values
(ii) the set where a r.v. within the family may take values
(iii) the "smallest standard superset" of where it may take values, e.g., R, R-plus, N, Z, etc
(iv) a combination of the above
I think (iii) makes type checks easy in cases where you combine random variables arithmetically, e.g., if you want to ask if they are both non-negative real etc you don't care about the precise support.
Whereas (i) is useful if you want to infer bounds or create composites.
An obvious sub-question is if there should be multiple domain specifications - e.g., one of the precise support, one of a more generic "scientific type".

Essentially we have implemented sub-question. So we have `support` and `type` **as well as** `distrDomain`

**Comment by fkiraly** [comment]
Yes, but which of these is the *specified* meaning ot `support`, `type`, and `distrDomain`? I don't think the documentation is precise on this, so unless you tell me what you have in mind, I can't really help...

**Comment by RaphaelS1** [comment]
Let's discuss on Tuesday

**Comment by fkiraly** [comment]
from the weekly meeting: we concluded we can get rid of it since the intended use case (union of support over all parameter settings) is more natural for "distribution families", which vanilla distr6 does no cover. To be revisited in the design there.
