### ISSUE TITLE
PosNaturals vs PosIntegers Consistency

### ISSUE THREAD

**Issue by RaphaelS1** [alan-turing-institute/distr6#117]
Currently we have a mishmash of Naturals, Integers, PosNaturals and PosIntegers as the supports of discrete distribution. It would be nice to pick one to be consistent, anyone have a preference?

**Comment by fkiraly** [comment]
Two questions:
- how is this inconsistent, exactly, with respect to which property?
- how is this related to #120 ?

**Comment by RaphaelS1** [comment]
> how is this inconsistent, exactly, with respect to which property?

Correct me if I'm wrong but the set of positive naturals (i.e. 1,2,3,...) and the set of positive integers are identical. Therefore in distr6 it would make sense if instead of using both as the supports of distributions or parameters, we just picked one and used that.

> how is this related to #120 ?

This issue relates to choosing which set to use. #120 is about choosing the correct symbol to efficiently differentiate between sets that do and do not include 0.

**Comment by RaphaelS1** [comment]
My updated feelings are thus:

The set of Positive Naturals {1,2,3,...} is denoted N+ this is clearly different from the set of Naturals {0,1,2,3,....} denoted by N.

Hence I think in distr6 we should do the following:

* For the set {0,1,2,...} we should use N
* For the set {1,2,3,...} we should use N+
* For the set {...,-3,-2,-1,0,1,2,3,...} we should use Z

Then the ambiguity of including 0 comes in, but this is issue #120.

As a separate issue (but for the sake of not opening up a new one) I have put the type of the categorical distribution as the complex set C as this is the 'most inclusive' set, although not strictly accurate. But maybe the set of naturals would be better to indicate discrete elements?
