### ISSUE TITLE
Distribution Full or Short Names as Constructors

### ISSUE THREAD

**Issue by RaphaelS1** [alan-turing-institute/distr6#119]
Currently the distribution full name is used as the class name and therefore in the constructor but might this be easier for the user if the short name is used instead (more in line with R stats and less typing).

e.g. instead of `NegativeBinomial$new()` -> `nbinom$new()`

**Comment by RaphaelS1** [comment]
Another argument for shortnames: the user doesn't have to remember which case the constructor is in, for example we have `LogLogistic`, `NegativeBinomial` and `Lognormal` but the short names are `llogis, nbinom, lnorm`

**Comment by fkiraly** [comment]
I think short names are more difficult to remember - with the easiest to remember convention perhaps ``all lowercase, full name'', though that one is cumbersome in use.
Do we have a "list disributions" method?

**Comment by RaphaelS1** [comment]
We do indeed `listDistributions()` and it gives the full and short names side by side, so a user can always look up the short-name

**Comment by RaphaelS1** [comment]
Another argument for using short name over full name is that doing so would mean having to re-name the class names to short-names, which would be beneficial in that currently we are masking the help pages of R-stats probability distributions, e.g. `?Binomial` is the help page for the `dbinom/pbinom/qbinom/rbinom` functions

**Comment by RaphaelS1** [comment]
I've gone very back and forth on this. On the one hand using the short names is more in-line with R standards but using the full-name is more in-line with OOP practices. Looking at mlr3's github I can see they opted for my original idea of the full-name in upper camel case, so I won't take any action now but we can possibly revisit after some feedback on distr6.

I have however added Roxygen aliases for common alternatives, e.g. `?Gaussian` and `?Normal` both point to the same documentation
