### ISSUE TITLE
Is distr6 big enough for a cheat-sheet?

### ISSUE THREAD

**Issue by RaphaelS1** [alan-turing-institute/distr6#123]
Or complex enough/targeting an audience who could benefit from one.

https://www.rstudio.com/resources/cheatsheets/how-to-contribute-a-cheatsheet/

**Comment by fkiraly** [comment]
I'd say: yes, definitely. Already a list of methods and distributions would be useful.

**Comment by RaphaelS1** [comment]
https://alan-turing-institute.github.io/distr6/reference/

https://alan-turing-institute.github.io/distr6/articles/webs/api_lifecycle.html

**Comment by fkiraly** [comment]
Ok, now you've forced me to admit that the *existing* list of methods and distributions is useful. Though of course not quite a cheat sheet yet.

**Comment by RaphaelS1** [comment]
Adding current draft 1 here for wider feedback

[cheatsheet.pdf](https://github.com/alan-turing-institute/distr6/files/3419281/cheatsheet.pdf)
