### ISSUE TITLE
Inf/Sup -> Lower/Upper

### ISSUE THREAD

**Issue by RaphaelS1** [alan-turing-institute/distr6#125]
Another lower priority question but still important for usability of the package to less-mathematical users. The methods `sup` and `inf` alongside supremum and infimum could confuse users who haven't seen them before. Perhaps 'upper' and 'lower' are simpler and thus more suitable?

For context this is in regards to distribution and parameter supports (i.e. upper and lower bounds of the support)

**Comment by fkiraly** [comment]
I think most users who know what a continuous distribution is will know, at least vaguely, what a supremum/infimum is? I.e., they will at least "know" that a supremum is a kind of maximum etc.

Don't think this needs action...

**Comment by RaphaelS1** [comment]
> I think most users who know what a continuous distribution is will know, at least vaguely, what a supremum/infimum is?

Based on my personal experience, R is taught as part of STAT101 in first year, but the term supremum/infimum wasn't used until third year courses. Similarly many users will know Normal distributions but be thrown by mathematical terms

**Comment by fkiraly** [comment]
Anyway, come to think of it: aren't distribution supports always closed sets, since they are defined as the complement of the largest open vanishing set?

Problem solved, no?

**Comment by fkiraly** [comment]
Or is this for parameter ranges?

**Comment by RaphaelS1** [comment]
Exactly the problem occurs with parameter ranges and hence we should have a consistent solution

**Comment by RaphaelS1** [comment]
Also distributions such as Wald divide by `x` hence if zero is included there's an error

**Comment by fkiraly** [comment]
Then the cleanest way might just be specifying the set, and prompting the user "error/warning - parmeter [parametername] must be contained in the following set: [set printout]"

**Comment by RaphaelS1** [comment]
In my opinion this is less clean than just using `SetInterval` objects as we do.
Currently each `SetInterval` includes methods:

* min - Minimum of set
* inf - Infimum of set
* max - Maximum of set
* sup - Supremum of set
* liesInSetInterval(x, bound ) -  If `bound == TRUE` then returns true if x <= sup & x >= inf; if `bound == FALSE` then returns true if x <= min & x >= max

**Comment by RaphaelS1** [comment]
So everything is automatically compared using `liesInSetInterval` and it is therefore unlikely a user will directly use the `min/max/inf/sup` methods. In hindsight there you're probably right and no action is needed
