### ISSUE TITLE
Log quantile or not?

### ISSUE THREAD

**Issue by RaphaelS1** [alan-turing-institute/distr6#128]
I find it annoying I have to even raise an issue for this, because the answer should be obvious but unfortunately isn't.

In R stats quantile functions they include the argument `log.p`. This, unless I'm very much mistaken, essentially applies the following transformation:

```R
qnorm(p, log.p = FALSE) = qnorm(p)
qnorm(p, log.p = TRUE) = qnorm(log(p))
```

Which of course results in `NaN`.

Now I would like to remove this argument completely because it is nonsensical but that goes against our design principle of keeping our arguments and methods as similar to R stats as possible. (At the moment the argument is just ignored, so it's there for consistency but a user changing it has no effect).

**Comment by fkiraly** [comment]
Confused - `qnorm` does exactly what it should, no? For example, `qnorm( -log(2),log.p = T)` produces the output 0 as expected?

**Comment by RaphaelS1** [comment]
That's how it's meant to be used?! Okay. I guess it has a purpose then... Ignore me!

**Comment by fkiraly** [comment]
Well, I'm not sure in which use case you would want this either, but it does something that's well-specified, at least.
