### ISSUE TITLE
Decomposing Mixtures

### ISSUE THREAD

**Issue by RaphaelS1** [alan-turing-institute/distr6#130]
I have just been reminded by @shliu99 that I forgot to add in a `decomposeMixture` (working name) method/function which was originally planned. 

Currently users can access the original wrapped models with the `wrappedModels` method but I think there are still good use-cases for having a `decomposeMixture` function too (not convinced this should be a method). 

In my mind this will be a function that returns a list of lists of the form:

```R
$discrete
$discrete$Model1
$discrete$Model1$Model
$discrete$Model1$Weight
```

And so on for more discrete models and analogously for continuous. Does this make sense or would it be more sensible to return weights and models separately? Or even to add another component for supports.

I know this is implemented in `distr` so @PeterRuckdeschel if you have any strong opinions from doing this, that would be appreciated!

**Comment by PeterRuckdeschel** [comment]
I would say the important method dispatch already happens through wrappedModels, so having decomposeMixture is indeed a helpful tool but implementing it as a function and not as a method is fine.

**Comment by fkiraly** [comment]
Hm, what exactly would be the use cases?

My question aims at trying to understand why a proper (nested) parameter interface is not sufficient - i.e., a sklearn or mlr style nested parameter interface that exposes the wrapped distributions' parameters as well as the mixture parameters in a unified way?

**Comment by PeterRuckdeschel** [comment]
I' m afraid, I am not familiar with mlr and sklearn and the paradigms used there.

I would see use cases for particular decompositions possibly derived from this.

Example 1 a decomposition into discrete and absolutely continuous part like in our UnivarLebDecClass. 

Example 2 a decomposition of the support into (strictly) positive, (strictly) negative and 0 part -- this is not as straightforward as example 1 as here one first has to artificially express a given distribution as a special mixture, but this results helpful for arithmetics acting on distributions, e.g., multiplication expressed as exp (log(X)+log(Y))  and reusing convolutions...  

To access particular mixture components indeed seems less useful.

**Comment by fkiraly** [comment]
@PeterRuckdeschel I see - though this means there are *two* important, distinct use cases, which also need to be mirrored in different architecture:

(1) accessing components of a composite (e.g., mixture), which has been constructed via a compositor. There is hence already an explicit declaration of what are the components through the nested compositor interface.
(2) accessing "components" of a distribution that has *not* been constructed via a compositor. For example, mixed distributions can always be decomposed into pure/continuous part, or a pos/neg/0 part However, in general one may not have defined these via compositors or wrappers, and there is no an explicit declaration of what these components are.

On a qualitative level, the difference is in decomposing something that (1) "has been composed" or (2) that we now "consider as a composite".

**Comment by RaphaelS1** [comment]
Closing this as it significantly overlaps with #147
