### ISSUE TITLE
implementation of log-pdf etc 

### ISSUE THREAD

**Issue by fkiraly** [alan-turing-institute/distr6#131]
A somewhat subtle but important issue when implementing log-pdf and log-variants of other distribution defining functions:

due to numerical resolution, there are substantial cases in which log-pdf should be implemented directly, rather than as the log of the pdf.

A prominent example is the normal distribution: 
the "true" value of `Normal$new()$pdf(100, log = T)` should be somewhere between -1000 and -2000, but currently it returns `-Inf`.

The "clean" way to implement this is via case distinction or case dispatch, based on the `log` argument. If `log = T`, then the formula used for computation is the "obvious" formula where the log is already cancelled with the exp, rather than log-of-exp which will result in numerical issues for too large arguments, compare `log(exp(1000))` which should result in 1000 but actually results in `Inf`.

**Comment by RaphaelS1** [comment]
This is actually one of the first things we discuss with @PeterRuckdeschel however bear in mind that R stats does not (as far as I am aware) make this distinction. Hence I believe this should be something we look at in v1.1, but if you think it should be dealt with in v1.0 I'm happy to discuss further

**Comment by fkiraly** [comment]
R base does make the distinction!

Compare
`dnorm(1000,log=T)`
and
`log(dnorm(1000))`

**Comment by fkiraly** [comment]
Doesn't need to be dealt with in 1.0 though, i.m.o., just putting it up as an issue.

**Comment by fkiraly** [comment]
A related interface design question: should there be a separate method `logpdf` etc, or do we dispatch by argument? The latter is a bit inconsistent tbh.

**Comment by RaphaelS1** [comment]
> R base does make the distinction!

I stand corrected

> A related interface design question: should there be a separate method logpdf etc, or do we dispatch by argument? The latter is a bit inconsistent tbh.
I'd prefer an explicit logpdf, though it's a bit late into the day for this now.

Not at all too late, this was always planned in the `ExoticStatistics` decorator, similarly to `survival` which may be analytical or numerical, both can be found in this decorator. `logpdf` was simply a casualty of working on other more common analytical results, but a good idea for v1.1

**Comment by RaphaelS1** [comment]
Note to self: Add check to see if analytical `log` given in d/p/q/r, if yes called in `dpqr(log = T)` if no then either errors if not decorated with CoreStats or imputes with `log(pdf(log = F))`
