### ISSUE TITLE
signature of setParameterValue?

### ISSUE THREAD

**Issue by fkiraly** [alan-turing-institute/distr6#132]
`setParameterValue` currently expects a single named list, which is a bit cumbersome and unintuitive.

I'd suggest to allow passing of a single list, but switch default usage to passing the list elements directly as arguments, for example
`myNormal$setParameterValue(mean = 2, var = 4)` should work.

This should be easily achievable by using `match.call` appropriately.

A very small caveat is dealing with the case of potential list-valued parameters, and setting of a single such parameter - which could be dealt with the convention that all parameters are named if and only if the non-list signature is used.

**Comment by RaphaelS1** [comment]
I had the same thought earlier today as I kept doing exactly what you suggested by mistake. This is now done, btw it's even quicker with

````R
    if(is.null(lst))
      lst <- list(...)
````
Then all the previous code works as before

**Comment by fkiraly** [comment]
... but don't you still need to check whether you're passing a list or trying to set a list-valued parameter?

**Comment by RaphaelS1** [comment]
No this can be bypassed by having the function as  `setParameterValue(..., lst = NULL)` and telling the user that if called as `setParameterValue(lst = list(someParam = 1))` then any additional arguments to `...` are ignored. And as the user has to name `lst` they are unlikely to mask anything accidentally
