### ISSUE TITLE
nested/composite parameter interface for truncation

### ISSUE THREAD

**Issue by fkiraly** [alan-turing-institute/distr6#133]
when truncating or huberizing, shouldn't the truncation boundaries become hyper-parameters of the truncated distribution, in addition to the parameters of the truncated distribution which are then nested?

**Comment by RaphaelS1** [comment]
I seem to recall we agreed against this previously, however it is do-able and is relatively quick to do. I can see good arguments both ways

**Comment by RaphaelS1** [comment]
Well actually, it is do-able however the current interface means that we would run into wrapping wrapper problems, in that say you want to do something like `truncate(huberize(Binomial,3,7,4,5))` then the parameter set would like something like:
prob ...
qprob ...
size ...
hubBinom_lower ...
hubBinom_upper ...
truncHubBinom_lower...
truncHubBinom_upper...

Which could be cumbersome. I'm inclined to leave how-is and if there is demand/feedback for this in the future then to push it to a later update

**Comment by fkiraly** [comment]
Inability to wrap a wrapper is usually an alarm sign of issues with the hyperparameter interface!

What I think the list of parameters should be in the doubly wrapped case is actually the oher way round:

wrappedname_wrappedwrappedname_prob ...
wrappedname_wrappedwrappedname_qprob ...
wrappedname_wrappedwrappedname_size ...
wrappedname_lower ...
wrappedname_upper ...
lower...
upper...

**Comment by RaphaelS1** [comment]
Wrappers can be wrapped! `truncate(huberize(Binomial,3,7,4,5))` is valid and works but the hyper-parameter interface for this doesn't simply because we haven't added the limits as hyperparameters. But for example please see the attached for a vectorized exponential and mixture of truncated binomial and huberized normal.
![Screenshot 2019-07-11 at 22 48 54](https://user-images.githubusercontent.com/25639974/61087654-2522cf80-a42e-11e9-93d1-c8286535f12f.png)

**Comment by fkiraly** [comment]
Ahh, ok - for a moment I feared we would have replicated the mlr2 problem, but the reason is just that the parameter passing isn't implemented for truncation/huberization (currently no outer wrap parameters).

**Comment by RaphaelS1** [comment]
> (currently no outer wrap parameters).

Precisely, hence something to consider for the future dependent on feedback etc.

**Comment by fkiraly** [comment]
I think tunable huberization limits are a good idea, especially for potential supervised learning applications, but there's no urgency.
