### ISSUE TITLE
Sets doesn't recognize redundant unions

### ISSUE THREAD

**Issue by fkiraly** [alan-turing-institute/distr6#134]
Shouldn't the sets interface recognize whenever you are constructing a redundant union? E.g., the union of R and R+ should just be R. This may irritate people in particular in the "mixtures" use case.

It's slightly more complicated, and perhaps out-of-scope for unions of intervals, or even their intersection/unions, because you need a rudimentary resolution calculus. 
If we ever do that, I'd advocate conjunctive normal form - which in the case of intervals in R as primitives can be further reduced/resolved to unions of intervals.

**Comment by fkiraly** [comment]
... in case anyone would like to volunteer making sets6 ...

**Comment by RaphaelS1** [comment]
I am very very *very* aware of the limitations of these sets, my mindset throughout was "if this works then I'm happy for now". Anyone who tries to use sets outside of how they are implemented will be incredibly annoyed 99% of the time. Sets6 is on my horizon

**Comment by fkiraly** [comment]
I know, but this becomes a bit annoyingly apparent when the user tries to run `myMixture$summary()` ...

**Comment by RaphaelS1** [comment]
Hm, given that any positive/negative set inherits from the more general (e.g. `PosReals` is a child of `Reals`) I could probably easily add a conditional that just says something like 'if x inherits from y then return y'

**Comment by RaphaelS1** [comment]
I've implemented the above. I'm closing this issue, not because sets isn't very flawed but because we know it is and already have plans to fix it in a new repo

**Comment by fkiraly** [comment]
Is inheritance always covariant with set containedness?

**Comment by RaphaelS1** [comment]
In this case yes, well no, but for all intents and purposes yes. `ExtendedReals` also inherits from `Reals` however no distribution has this as a type or support so it shouldn't be a problem
