### ISSUE TITLE
Renaming variable `x1` to `x`

### ISSUE THREAD

**Issue by RaphaelS1** [alan-turing-institute/distr6#137]
The current implementation of pdfs and cdfs is with the formals `$pdf(x1,...)` then for multivariates this extends to `$pdf(x1,x2,...,xn,...)`. `x1` is used as the first formal for univariates for consistency with multivariates. However we could consider changing this to `$pdf(x,...)` and multivariates `$pdf(x,x2,...,xn,...)`, which is more consistent with R stats.

**Comment by fkiraly** [comment]
why not just call everything `x`, and what `pdf` expects is an element of `support`?

**Comment by RaphaelS1** [comment]
Sorry, I don't understand this

**Comment by fkiraly** [comment]
If the distribution is N-variate real, the expected type of `x` is an N-vector of floats.

**Comment by RaphaelS1** [comment]
What about if you want to get the `pdf` evaluated at two points?

**Comment by fkiraly** [comment]
I know, I was thinking about how vectorization would work.
That could be just "list of single input"?

**Comment by RaphaelS1** [comment]
Currently say you want the pdf of a univariate at two points: `pdf(c(1,2))` or a multivariate at two points `pdf(1:2,1:2)`

**Comment by RaphaelS1** [comment]
I think the current method works well, vectorizes nicely and interfaces with R stats naturally

**Comment by fkiraly** [comment]
that would be `pdf(list(1,2))`, or `pdf(list(c(1,1),c(2,2))`

**Comment by RaphaelS1** [comment]
Wrapping it in list seems unnecessary...

**Comment by fkiraly** [comment]
But it doesn't generalize to distributions with arbitrary domain.

What if you have a distribution over strings? Or over images? Or, even, distributions over distributions?

**Comment by fkiraly** [comment]
My concern is that we're cutting off extensibility beyond the reals.

**Comment by RaphaelS1** [comment]
It works for the categorical distribution which uses strings!

**Comment by fkiraly** [comment]
As a usability hack, one could say that vectors instead of lists are fine if the distribution is real, univariate, or categorical. And, that data frames (rows = samples) are fine if the distribution is multivariate.

**Comment by RaphaelS1** [comment]
But the current method works if the distribution is multivariate and vectorizes well. It even works for matrixvariate (which I think images likely are)

**Comment by fkiraly** [comment]
How would it work for matrixvariate? Do you pass a 3D tensor?

**Comment by RaphaelS1** [comment]
Essentially yes

**Comment by fkiraly** [comment]
But then it's inconsistent since you're not calling arguments `x11`,`x12`,`x13`, etc

**Comment by RaphaelS1** [comment]
This is very much a 1.1-1.2 update, for now we should wait for feedback regarding the current implementation. It may be users prefer that the first argument is a length n-vector corresponding to number of variates and that every other argument is evaluation at more points.

Sorry you're right, it would actually look like passing a vector to each argument and then to extend this to evaluation at multiple points you instead pass a matrix to each argument

**Comment by fkiraly** [comment]
The only interface that's consistent across all use cases which I can see is:
(i) default call is single argument (e.g., `x`), of type "inhabitant of `support`"
(ii) vectorized call is list of arguments as in (i)

**Comment by RaphaelS1** [comment]
At this stage I think a change like this would completely break reverse dependencies, i.e. `mlr3proba`, and I'm not convinced it's a good idea anymore. There are very few use-cases where it is problematic (the 3D-tensor-variate e.g.) and in all these cases, users will be advanced enough to use the `do.call` and `paste` method like in `mlr3proba`. It isn't ideal but I don't see any better alternative. I will close this issue in a week if there are no further developments

**Comment by RaphaelS1** [comment]
/remind me in to close in 1 week

**Comment by RaphaelS1** [comment]
See #179 for a more generalised discussion about this and for conclusions.

**Comment by RaphaelS1** [comment]
This is now #179
