### ISSUE TITLE
Calling Kernel$new() results in an error

### ISSUE THREAD

**Issue by jdeenichin** [alan-turing-institute/distr6#140]

**Comment by RaphaelS1** [comment]
`Kernel$new()` should throw an error as it is an abstract class, to implement custom Kernels users should use `Distribution$new()` (as Kernels are just a sub-case). Can you please confirm that the error message is something along the lines of "kernel is an abstract class"

**Comment by jdeenichin** [comment]
Yes, the message I get is: "Kernel is an abstract class that can't be initialized. Use listKernels() to see the kernels currently implemented in distr6.".

**Comment by RaphaelS1** [comment]
I've updated the documentation to make this clearer. Thanks !
