### ISSUE TITLE
cdf of discrete distributions is 0 between integers

### ISSUE THREAD

**Issue by RaphaelS1** [alan-turing-institute/distr6#143]
Whilst this is correct of the pdf, this does not hold of the cdf. A better outcome would be such that `x$cdf(2.4) == x$cdf(2)`. Although this isn't strictly true as it doesn't exist between integers, it probably makes more sense than returning zero, I think.

**Comment by fkiraly** [comment]
This depends on what you consider the domain of the distribution.

If the domain is real, indeed the `cdf` should default to rounding down.

If the domain is the integers, the `cdf` should only be defined for integer inputs.

This distinction may make more sense for complex domains though, for integers/reals there might not be a practical difference implied through this formal difference.

**Comment by RaphaelS1** [comment]
Hm, so between integer inputs the `pdf` is 0 but the `cdf` is NaN? Or should both be `NaN`? If we go by wikipedia as the "lay-community standard" then we should round down, see [here](https://en.wikipedia.org/wiki/Poisson_distribution#/media/File:Poisson_cdf.svg)

**Comment by fkiraly** [comment]
That depends on which formal convention we adapt - always considering the distribution as one over the reals, or allowing for user specified difference between cases "real" and "integer".

In the "real" case, pdf should be 0, and cdf should be rounded down.
In the "integer" case, both should return `NaN`.

**Comment by fkiraly** [comment]
Actually, there should be no pdf. It should be a pmf, as a distribution on the reals, this only has a non-trivial pure part and no absolutely continuous part.

**Comment by RaphaelS1** [comment]
> Actually, there should be no pdf. It should be a pmf, as a distribution on the reals, this only has a non-trivial pure part and no absolutely continuous part.

Formally this is true but the method is always called `pdf` in distr6

> In the "real" case, pdf should be 0, and cdf should be rounded down.
In the "integer" case, both should return NaN.

My current thoughts are that R stats adopts the former and as do most visualisations of discrete cdfs, hence I think `pdf` should return 0 between integers and `cdf` should be rounded down

**Comment by fkiraly** [comment]
>Formally this is true but the method is always called pdf in distr6

See #147 which I just wrote - I wasn't too concerned when we first designed this, but come to think of it it is a bit strange that we are referring to pmf by pdf. There may even be good API rationales for not doing this (i.e., the mixed case).

>My current thoughts are that R stats adopts the former and as do most visualisations of discrete cdfs

If you mean the default behaviour should be "consider it on the reals if the user asks for it", that's a valid stance. I wonder whether there are any use cases where this comes back to bite us, but I can't think of any.

**Comment by RaphaelS1** [comment]
> See #147 which I just wrote - I wasn't too concerned when we first designed this, but come to think of it it is a bit strange that we are referring to pmf by pdf.

This is how it's done in R stats, distr and Distributions.jl however and I think this is an instance where we should go with the community norm.

> If you mean the default behaviour should be "consider it on the reals if the user asks for it", that's a valid stance. I wonder whether there are any use cases where this comes back to bite us, but I can't think of any.

Yes. R stats actually returns `0` with warning for `pdf` between integers and rounds down without warning for `cdf`
