### ISSUE TITLE
Array distribution for vectors

### ISSUE THREAD

**Issue by RaphaelS1** [alan-turing-institute/distr6#144]
Currently the `ArrayDistribution` is a special case of the `ProductDistribution` where each individual distribution is of the same distribution type. However it also makes sense to have an analogue for the `VectorDistribution`. Should this be given the same name but with an extra argument for determining if the result should be a `Vector` or `Product` distribution or make a new wrapper?

**Comment by fkiraly** [comment]
I think we need to be careful about the distinction between:
(i) multivariate, and so cdf goes from array to one number
(ii) container of multiple distributions, so cdf goes from array to array

Currently, `ProductDistribution` and `ArrayDistribution` exhibit behaviour as in (i), while `VectorDistribution` exhibits behaviour as in (ii), which seems inconsistent at least in naming.

I think we should distinguish "product distributions" and "distribution products", or however one wants to name these two cases. @PeterRuckdeschel, do you know of clean terminology and mathematical framework (e.g., category theory) to distinguish these?

To me it seems: (i) is a product in the category of distributions, while (ii) is the product in the category of objects (i.e., just a tuple)

**Comment by RaphaelS1** [comment]
> To me it seems: (i) is a product in the category of distributions, while (ii) is the product in the category of objects (i.e., just a tuple)

I agree.


To be clear, currently implemented are:
* `ProductDistribution` - Multivariate, f(x, y) = f_x(x)f_y(y)
* `ArrayDistribution` - A special case product distribution where all f_x are the same probability family (e.g. Binomial but possibly different parameterisations)
* `VectorDistribution` - A collection of distributions, i.e. vectorised distributions. Perhaps a smarter name choice would be `DistributionCollection`, analogously to the more-familiar 'collection of sets -> setcollection'

I'm proposing to additionally implement a special case vector distribution where each distribution comes from the same probability family, e.g. in probabilistic modelling a vector of Delta distributions.

I wonder if this could be greatly simplified by deprecating `ArrayDistribution` and instead adding named arguments to `ProductDistribution` and `VectorDistribution` such that they both take the same arguments, using Product as the example:
```R
ProductDistribution$new(distList = NULL, distribution = NULL, paramList = NULL)
````
Then the user can either pass a list of distributions to `distList` or can pass the name of a distribution family to `distribution` and a list of parameters to `paramList`.

BTW there is a reason why we have the `distList` named argument as opposed to `...` but can't remember why off the top of my head...

**Comment by fkiraly** [comment]
Part of the problem is naming: I've thought about this, and perhaps clearest terminology is to talk about "tuples of distributions", or "distribution tuple" in case (ii).

Case (i), is formally, a tuple distribution, i.e., a distribution *over* tuples, but that might be confusing terminology, hence "product" is perhaps the best.

In terms of formal types, the difference is between (i) `Distr(Tuple(X,N))` and (ii) `Tuple(Distr(X),N)`, and similar for arrays etc, it I can make up a Julia-like ad-hoc higher-order type language.

In terms of interface, I agree with the good idea to simplify this down to the two defining cases - we don't need multiple wrappers depending on input format.

There are similar conventions in a number of R functions (e.g., constructor of data frame) that even if the internal format is vectors/lists of equal length as arguments A, B, C, if a single element is passed to one of the arguments, say B, while others are of length N, the argument of B is repeated to fill the length.

The one open question that remains here is how we would deal with the case where there are arrays/matrices, e.g., distributions over matrices vs matrices of distributions, and where the "intermediate" case of a matrix where you have a tuple of column-vector-valued distributions which also has matrix shape.

**Comment by fkiraly** [comment]
Regarding the last bit: one could follow the convention that mixed cases are treated by nesting first the compositor (i) and then (ii), i.e., you would have `Tuple(Distr(Tuple(X,N)),M)` etc.

The shape constraints could be solved by introducing an optional "dims" argument, which is a vector of integers, and if not given defaulting to the shape of the highest dimensional object passed (either `distList` or `paramList`).

Which would, however, introduce a secondary conundrum, namely "what's our convention on the N-D generalization of `list`".

**Comment by RaphaelS1** [comment]
> In terms of interface, I agree with the good idea to simplify this down to the two defining cases - we don't need multiple wrappers depending on input format.

In which case we remove the `ArrayDistribution` and don't have to worry about the naming problem of that. However I am still considering changing `VectorDistribution` to `DistributionVector` or `DistributionCollection` as the former seems to indicate a specialised Distribution that is a vector whereas the latter seem to indicate a vector of distributions, and more commonly one would refer to a 'numeric vector' as opposed to a 'vector numeric'

**Comment by fkiraly** [comment]
we still need to worry about constructor/method signature though.

**Comment by RaphaelS1** [comment]
Both vector and product distribution have identical constructors described as above

**Comment by PeterRuckdeschel** [comment]
Sorry for jumping in late -- was on holiday for a couple of days...

I think you already solved this issue quite adequately. 

I, too, see two aspects of the issue: (1) a consistent and self-explanatory naming convention and (2) an efficient interface. (1) is more for human readability while (2) may also have an impact on performance. 

For (1) AFAIK there are no well-established concepts so far. On the theoretic side probabilities being defined on sigma algebras, the items you assign a probability to only need to be sets, so can, additionally, have whatever structure (vectors, arrays, matrices, ---they may even themselves be measures). I think the convention to use a prefix for the structure (ArrayDistribution) is fine, but I am not aware of this convention being "standard". The same goes for the other direction: Of course you may group distributions to whatever set structure (vectors, arrays, matrices) and again the convention you propose is fine but again I am not aware of this being standard.

For (2) my computer science background is too limited to be able to judge the performance impact of different implementation strategies. The issue I see is basically how to efficiently manage partially evaluated expressions -- e.g. an array of distributions could be operationalized by specifying an array of cdf's (as functions), which, once evaluated return an array of numbers (floats/doubles). But before evaluation the array consists of not yet evaluated expressions. Now, quite often the (partially) evaluated entries of the array will only vary slightly from entry to entry, so it may be worthwhile thinking of good strategies to reuse parsing / evaluation information from "neighboring" entries.
[Base] R has little supporting infrastructure for this -- the construction which you can use out of the box is lists which you can construct from arbitrary data types. Vectors/matrices/arrays is much less straightforward: you can indeed construct vectors of pretty much arbitrary entry type; however quite often such data types tend to loose dimension attributes after the slightest modifications; so to warrant some safety you are on your own quite quickly.
