### ISSUE TITLE
strprint for Distributions needs to be more dynamic

### ISSUE THREAD

**Issue by RaphaelS1** [alan-turing-institute/distr6#145]
See the attachment for an example of a silly print output because the vector distribution contains 500 distributions.

The `strprint` method should mitigate against this as much as possible by limiting number of displayed parameters, note this only occurs in `Wrappers` hence can be over-loaded at this level

![Screenshot 2019-07-30 at 18 06 20](https://user-images.githubusercontent.com/25639974/62150025-e1b4d600-b2f4-11e9-8685-90eb0316d414.png)

**Comment by fkiraly** [comment]
I don't know what you mean, this is a perfectly readable and user-accessible output.

**Comment by RaphaelS1** [comment]
But this would not be consistent with other distributions, I agree the `summary` method should definitely do this. BTW this specific problem is solved in the 'array' set-up (i.e. #144 )

**Comment by fkiraly** [comment]
Hm, for consistency one could replace just the "parameters" part with a more tabular/systematic display and leave the rest as-is?

**Comment by RaphaelS1** [comment]
I believe this is solved in the latest release
