### ISSUE TITLE
Error when creating object: "locked environment"

### ISSUE THREAD

**Issue by csrvermaak** [alan-turing-institute/distr6#150]
Please advise - I run into an error. 

Reprex:
```
library(distr6)
population = distr6::Normal$new(var = 1, mean = 1)

```

Result:
```
Error in private$.setSymbol <- setSymbol(paste0(getR6Class(self, pos = environment()))) : 
  cannot add bindings to a locked environment
```

Am I doing something wrong? This example is from the documentation?

**Comment by RaphaelS1** [comment]
Hi thanks for opening this issue, so is the only thing you're running those two lines? This works perfectly locally so could you please tell me which version of distr6 you are currently running and operating system etc. ?

**Comment by csrvermaak** [comment]
Hi Raphael 

See below:

```

library(distr6)

-----------------------------
	distr6 v1.1.0

Get started:	?distr6
Changelog:	distr6News()
-----------------------------


Attaching package: ‘distr6’

The following object is masked from ‘package:grDevices’:

    pdf

The following objects are masked from ‘package:base’:

    mode, truncate

> population = distr6::Normal$new(var = 1, mean = 1)
Error in private$.setSymbol <- setSymbol(paste0(getR6Class(self, pos = environment()))) : 
  cannot add bindings to a locked environment

```

**Comment by RaphaelS1** [comment]
Thanks for that, I know which part of the code the error is in, and I'm guessing if you try and run `distr6::Reals$new()` you will get the same error. The strange thing is that I haven't heard from anyone of this error before and the code hasn't changed since v1.0, which was tested on Windows 10 R3.4.0.

The only thing I can think of is perhaps you are running an old version of `R6`, could you let me know which version you are running? `utils::packageVersion("R6")`

**Comment by csrvermaak** [comment]
Yes, I do get the same error on `distr6::Reals$new()`

```
utils::packageVersion("R6")
```

Result:
```
[1] ‘2.2.2’
```


Any ideas? Thanks for helping.

**Comment by RaphaelS1** [comment]
Can you try upgrading your R6? My thought process is that the error is occurring due to something in R6 not allowing a `Set` to be constructed, I'm running v2.4.0 so it's possible that distr6 should depend on a version higher than 2.2.2.

**Comment by csrvermaak** [comment]
Unfortunately upgrading to R6 v2.4.0 didn't work:

```
Microsoft R Open 3.5.0
The enhanced R distribution from Microsoft
Microsoft packages Copyright (C) 2018 Microsoft Corporation

Using the Intel MKL for parallel mathematical computing (using 4 cores).

Default CRAN mirror snapshot taken on 2018-06-01.
See: https://mran.microsoft.com/.

> library(distr6)

-----------------------------
	distr6 v1.1.0

Get started:	?distr6
Changelog:	distr6News()
-----------------------------


Attaching package: ‘distr6’

The following object is masked from ‘package:grDevices’:

    pdf

The following objects are masked from ‘package:base’:

    mode, truncate

> 
> population = distr6::Normal$new(var = 1, mean = 1)
Error in private$.setSymbol <- setSymbol(paste0(getR6Class(self, pos = environment()))) : 
  cannot add bindings to a locked environment
> 
> distr6::Reals$new()
Error in private$.setSymbol <- setSymbol(paste0(getR6Class(self, pos = environment()))) : 
  cannot add bindings to a locked environment
> 
> utils::packageVersion("R6")
[1] ‘2.4.0’
```

**Comment by RaphaelS1** [comment]
Okay, sorry this is happening, it is very weird.. I'll take a deeper look at this and hopefully have some sort of solution soon

**Comment by RaphaelS1** [comment]
I have a small update: distr6 is currently in the process of being uploaded to CRAN. The windows version is still not fully updated, which means that bugs could definitely be being introduced in the installation process. The windows binaries often take a couple of days to upload. I will post here again when they are fully uploaded, and it should work normally then

**Comment by RaphaelS1** [comment]
Just to update you. CRAN have just told me that the update will be available on windows within 24hours, clearly whichever version you have installed should never have been installable!

**Comment by RaphaelS1** [comment]
The update is now live, it should work with no errors now

**Comment by csrvermaak** [comment]
Thanks Raphael, much appreciated.
