### ISSUE TITLE
"GeneralizedDiscrete Distribution"

### ISSUE THREAD

**Issue by RaphaelS1** [alan-turing-institute/distr6#156]
From coding mlr3proba it is clear that a new distribution is required. Originally I had been hard-coding complete matrices into the `pdf` and `cdf` functions but this was messy. The problem is that the `Distribution` constructor expects general functions for `pdf` and `cdf` and therefore to do any sort of binary search has to be performed within the function itself, which is inefficient. I thought about giving the `EmpricialDistribution` a `sample.frame` constructor which takes as input a data.frame with columns: samples, pdf, cdf. But this ends up losing information as we now no longer know the number of events that occur (as it is generative and not observed).

Hence I propose a new distribution `GeneralisedDiscrete` or something like that which takes a single argument `data.frame` which has columns as suggested above. Then it becomes very easy to construct this from an empirical estimator, e.g. Kaplan-Meier, which returns a matrix of times and survival probabilities.

Thoughts?
(@fkiraly)

**Comment by RaphaelS1** [comment]
As a follow-up, I presume the variance is then the population variance i.e. dividing by N not N-1

**Comment by fkiraly** [comment]
Correct (sorf-of) - the variance of an empirical distribution is identical with the standard *biased* estimate that divides by N, but this is an estimate *of* a hypothetical *population* variance.

**Comment by fkiraly** [comment]
Regarding the general design/object - let's discuss this tomorrow verbally, I feel we need a whiteboard.

**Comment by fkiraly** [comment]
As discussed today: I agree with @RaphaelS1 's suggestion that empirical distributions (more precisely: weighted discrete distributions over the reals) should be their own class.

**Comment by fkiraly** [comment]
(though I'd call it `WeightedDiscrete` or something similar, perhaps have a separate class `Empirical` for the uniform/unweighted case?)
