### ISSUE TITLE
Consider implementation of callr or evaluate for error propagation

### ISSUE THREAD

**Issue by RaphaelS1** [alan-turing-institute/distr6#162]
As discussed in one of our initial conversations with @PeterRuckdeschel , it would be nice to have a feature that can capture and provide proper traceback in case of errors. With more experience working on `mlr3proba` I can now suggest we use one of the packages `evaluate` or `callr` to aid in this if we decide that it is worth the implementation effort, which is unclear at this point how extensive that would be.

**Comment by fkiraly** [comment]
hm, whether it's worth the effort depends on frequency, type, and "mysteriousness" of errors for a user or advanced user, and how likely they are to become a problem in a package relying on `distr6` (e.g., `mlr3proba`). Lacking a large user base at the moment, the only way to get a solid idea would be user testing, or expert educated guesses?

**Comment by fkiraly** [comment]
... where the latter probably means either @RaphaelS1 or @PeterRuckdeschel guessing? Or, @berndbischl, if he has the time to guess.

**Comment by RaphaelS1** [comment]
`mlr3proba` already does this with `evaluate` and `callr` as per the `mlr3` workflow. Therefore the more precise question is: does `distr6` internally need this sort of tracking? Arguably there is no process too complicated currently implemented but one such workflow could be using the `ExoticStatistics` decorator on a convolution of two custom distributions (that could be derived from data) and therefore, which would require at least five distinct processes

**Comment by berndbischl** [comment]
> `distr6` internally need this sort of tracking?

i am unsure what complex and expensive beasts you are currently planning to put in distr6, but from my current understanding i dont see the benfit of adding stuff like callr to it.

for mlr3proba: definitely, yes. but as you said you get this from mlr3 for free

**Comment by RaphaelS1** [comment]
At this stage, everything is fairly trackable. But as the distr team (@PeterRuckdeschel, @stamats) discovered: after a pipeline involving distribution composition, estimation, modelling, etc. it can quickly become hard to track errors.

I don't think it's required at this time, especially as your comment makes it sound like this tracking is not easy to implement, I just want to make sure that if there is a foreseeable future in which it is required, then we don't wait until it's too late (i.e. more complicated) to implement

**Comment by berndbischl** [comment]
maybe i also misunderstood. mlr3 mainly uses callr to call a (complex) thing (= the ML algo) in a separate R process to encapsulate this and protect the main mlr3 process. and this made tracking of errors / tracebacks actually harder.

why do you think this makes tracking better (i understand your general problem though, lots of indirection causes confusion)

**Comment by RaphaelS1** [comment]
Ah maybe that makes it more complicated then and I misunderstood how it works... 

The original ideas suggested by Peter was to have dynamic commenting - see https://github.com/alan-turing-institute/distr6/issues/16

Which has the benefit of tracking how compositions are created over the workflow but requires a lot of hard-coding. 

Whilst that covers tracking to describe models it does not cover how to process errors. For example (as happened to me today) say we are fitting a parametric survival model (which fits on a log-scale) but the estimated parameter is outside of the range on the original scale (which happens occasionally) then it would be nice to, say, truncate this estimated value and record this somewhere in the object. I guess similarly to how each model in `mlr3` has a `log`.

**Comment by berndbischl** [comment]
not sure if you are overeningeering this. have you considered using the same logger as mlr3 and adding debug messages to the logger?

**Comment by fkiraly** [comment]
@berndbischl , not sure if I'm adding any clarity above what @RaphaelS1 is saying, and whether I understand him correctly, but I think the gist is that distributions can be just as complex pipelines/composites as prediction algorithms. Consider a truncated inhomogenous mixture where the components may include a domain transformation (e.g., exponential or Cox-Box).

Additionally, there are decorators or wrappers which may impute slots, e.g., for distribution-defining functions (pdf, cdf, etc), or summaries/statistics (e.g., moments).

Issue #16 contains some use case examples by @PeterRuckdeschel, but note that this is from a time before the interface had consolidated.

**Comment by berndbischl** [comment]
@fkiraly i get this already, it a complex piece of code, with lots of indirections.
then tracing errors can become very hard. thats bad, but a known fact.
asking, what to do against that / to mitigate that is natural.

my point here is: most of the tools that have been mentioned so far, do not help for that matter. callr we use in mlr3, because the called pieces of code are a) expensive to evaluate b) can completely crash the R session. and in b) you then not only lose control but usually also the trace. 
this is why we use callr. and you do not have that problem, here. i think

**Comment by PeterRuckdeschel** [comment]
Sorry to jump in very late -- with our term just having started and me as the current director of our institute, my desk was a bit overloaded -- with no helpers like evaluate or callr available ;-)

Just to be precise about our [distr] approach -- we never thought of encapsulating pieces of code in a separate evaluation environment which indeed can be helpful but on the other hand leaves up to you maintenance of separate calling stacks / tracers / and, in particular, information exchange between the different evaluators. As noted by Raphael and Franz, my idea was rather to have a (potentially, later on) parsable logger, to be able to trace more accurately how objects were built/created one from the other. 

In this issue, I had some offline conversation with former R core member Duncan Murdoch (who authored the srcref, Murdoch, D. (2010). Source references. The R Journal, 2/2: 16-19) on the possibilities to have comments/ srcrefs in automatically generated code, which was our [distr] approach to implement this logging mechanism. More precisely, as in distr, we generate code (like cdf-, quantile-, rng-, and density functions) automatically, our idea was to attach this logging information in form of automatically generated comments to this code. The easiest way, according to Duncan, is use of tmpfiles to do this, but still this would involve non-standard infrastructure.

Sure there could be other approaches to achieve this logging. The key insight for me, though, was that aside from the main focus of distr (in our case) or distr6 in Franz'es and Raphael's case, one would in addition take over the task to maintain such additional infrastructure. 

If I understand Raphael and Franz correctly, they were seeking such infrastructure already provided (and maintained) by someone else to be able to focus on distr6, which I think is quite reasonable. 

So question would be: Would you @berndbischl know of such infrastructure?

**Comment by berndbischl** [comment]
No sorry I do not. My personal feeling is also that the complexity of distr6 does not warrant something like this. Standard loggers and traces should really be fine for a project like this.
