### ISSUE TITLE
as.data.table() breaks S3 dispatch

### ISSUE THREAD

**Issue by mllg** [alan-turing-institute/distr6#172]
After loading distr6, my S3 methods for `as.data.table()` are not working anymore. Why are you are overloading the generic?

**Comment by RaphaelS1** [comment]
That's very strange it should be dispatch and definitely not overloading. Weird that this hasn't come up before. I'll take a look thanks

**Comment by mllg** [comment]
This is `as.data.table` after loading distr6:

```r
function (object)
{
    args = as.list(match.call())
    args[[1]] = NULL
    args$object = NULL
    do.call(get("object")[["as.data.table"]], args)
}
<bytecode: 0x5641545ace88>
<environment: 0x564154774b48>
```

Note that the environment is **not** your package namespace. That's odd.

**Comment by RaphaelS1** [comment]
It's an R62S3 problem. Clearly one of the distributions has a method called as.data.table. R62S3 is currently called assuming no functions are overwritten but as as.data.table is incorrectly defined as a method this is being overwritten

**Comment by RaphaelS1** [comment]
Fixed but this brought up a very strange property of `as.data.table` and interactions with R6, which maybe you encountered. When using `as.data.table` as a method and then subsetting the table, the result is a data.table, but when using `as.data.table` with dispatch and then subsetting the result is a a list. One seems to wrap it in another list.

**Comment by fkiraly** [comment]
being slightly late to this - would it be sensible to have `R62S3` check whether it overloads an existing S3 method, and by default not overloading (and/or in addition doing something smart, such as add to dispatch tree)?

**Comment by RaphaelS1** [comment]
That is exactly what `R62S3` does. But I turned this feature off because when defining all the methods I deliberate did so making sure no masking would occur. However I made the mistake of forgetting that `as.data.table` was programmed as a method

**Comment by fkiraly** [comment]
Nice - implementing my great suggestions before I even make them :-)
