### ISSUE TITLE
Consider minor/possibly major update to convert public methods to active bindings

### ISSUE THREAD

**Issue by RaphaelS1** [alan-turing-institute/distr6#176]
I think that there are several cases where active bindings will be more intuitive than public methods. I think distribution methods such as `mean`, `var`, etc. should stay as public methods but accessors such as `properties` and `traits` may more naturally be active bindings. This will require a lot of work, but I think that whilst `mlr3proba` is the only dependency, this is probably the best time to do it

**Comment by RaphaelS1** [comment]
Read-only public methods to consider changing to active bindings:

* decorators()
* traits()
* valueSupport()
* variateForm()
* type()
* properties()
* support()
* symmetry()
* sup()
* inf()
* dmax()
* dmin()
* kurtosisType()
* skewnessType()

**Comment by RaphaelS1** [comment]
This should only be done after https://github.com/RaphaelS1/R62S3/issues/7 is closed

**Comment by RaphaelS1** [comment]
Note: We can't simply deprecate the public methods as active bindings can't have the same name as public methods. Therefore in doing this there is a risk to backwards-compatibility. However, the functions from R62S3 will be unaffected so any possible breakage should be fairly minor.

It is unclear whether the pros of this change (more consistency with other parts of R, more consistency with mlr3proba, perhaps more intuitive) outweigh the cons (may affect backwards compatibility).

**Comment by fkiraly** [comment]
Don't know - I thought the core interface was good as is. 
Perhaps something for distr7 (built with R7) or a major version update?

**Comment by RaphaelS1** [comment]
The only reason I have to suggest changing this now is an inconsistency between mlr3proba, distr6, set6. By example say we have a trained learner, `lrn`:

```R
# active binding in mlr3proba gets distribution
lrn$distr

# public method in distr6 gets set
lrn$distr$support()

# active binding in set6 gets set maximum
lrn$distr$support()$max

# or public method in distr6 gets maximum
lrn$distr$sup()
```

**Comment by RaphaelS1** [comment]
You can see the flicking between active bindings and public methods, as well as inconsistencies in set6 and distr6 for calling the same quantity, this latter is less problematic as they are different packages, but I can imagine the former becoming frustrating as the user is forced to remember which packages use active bindings and which use public methods

**Comment by fkiraly** [comment]
I see - that's a good argument i.m.o. to homogenize interfaces.
Do I interpret your choice of examples correctly in the way that it would mostly affect distr6?

**Comment by RaphaelS1** [comment]
Well it doesn't affect set6 at all as this is at the top of the stream. It affects distr6 the most as this is the only one using public methods, so the two sources of potential confusion are i) a user of distr6 interacting with the distribution support, type or parameters, ii) users of mlr3proba interacting with distributions and then supports etc. Of course this becomes the most problematic if there is a paradox rewrite
