### ISSUE TITLE
Rcpp Re-write

### ISSUE THREAD

**Issue by RaphaelS1** [alan-turing-institute/distr6#188]
I can admit when wrong, and I was wrong. An Rcpp implementation would be vastly more efficient and reduce some major bottlenecks. Whilst working on #179 I realised that when trying to unify every package, some major bottlenecks were created. The solution is to either make use of Rcpp for faster implementation, or to remove several checks and helpers that have helped make distr6 a good, scalable package.

A short background to the problem:

1. d/p/q/r

Some packages automatically check to see if supplied values to evaluate are within the distribution support, some do not. To get around this, `distr6` does the following (e.g. for cdf):

```R
out = length(x)
out[x < min] = 0
out[x >= max] = 1
out[x >= min & x < max] = cdf(x[x >= min & x < max])
````
But benchmark experiments clearly indicate that actually it would be vastly more quicker (almost 10 times quicker) to use Rcpp and loop over all `x` with the conditionals above.

2. `VectorDistribution`

These are used throughout `mlr3proba` and are currently causing significant bottlenecks in evaluating predicted models. One solution here could be to use Rcpp, but this may not be ideal as it would require passing an R function as parameter to Rcpp which creates significant overheads and may not be faster than current. Another is to create a function that vectorizes for parameters for `VectorDistributions` when internal distr is of same type, but this could be quite complex. It is worth benchmarking Rcpp vs status-quo and then decide how to proceed. This relates to #169

**Comment by fkiraly** [comment]
>I can admit when wrong, and I was wrong.

This is, in general, a sign of wisdom ... but I don´t remember which precise instance of you having been wrong you are referring to - for me to understand/learn, would you mind pointing that out?

**Comment by RaphaelS1** [comment]
When originally deciding how to implement new distributions, I chose R over C because R is more transparent and benchmark experiments indicated R was faster. The problem is that these were fairly naive experiments that were in fact, wrong. A secondary problem arrived when trying to unify d/p/q/r and vectorising inputs, which is the example given above.

So now if redesigning, a decision has to be made to decide how many checks and changes the public d/p/q/r methods make, and how many should be left to the private methods. The trade-off is as follows:

1. Maximimise public & minimise private: Then no analytical results for `lower.tail` or `log` are used, these are just wrapped around private methods. We also first check to see if the points to evaluate lie within the distribution support, if they do then only these points are evaluated and others are set to `0/1`
2. Minimise public & maximise private: Then every implemented distribution must be expected to have the same inputs (`..., log, lower.tail`) and must be able to handle evaluates outside of the distribution support.

I'm currently working towards the following midpoint:

1. Private `d/p/q` functions should include as arguments **either** `...` **or** `..., log, lower.tail`. In the case when `log` is included then a private flat is set to `TRUE`, which means an analytical `log` and `lower.tail` expression is available

But there is now a problem with if public `d/p/q` methods should use Rcpp to detect if the points to evaluate are within the distribution support. The reason for doing this is that it is inconsistent currently if/how implemented distributions handle this. e.g. how real-valued inputs are evaluated in `dbinom/pbinom`. Ideally we would use Rcpp but this doesn't work as it requires an R function to be passed as a parameter to C which creates an even larger bottleneck. Therefore it probably makes more sense just to put the onus entirely on the private d/p/q methods

**Comment by RaphaelS1** [comment]
Note to self: 

Re-write all internally implemented distributions with `Rcpp` and vectorise over `x` and `parameters`, see `dbinom` e.g. as example of how this should return for use in `VectorDistribution`

**Comment by fkiraly** [comment]
Regarding domain check:
should this not simply be a standard check inherited from base class, where domain is a `set6` object, and all functions are checking whether you are in the respective domain by invoking containedness method of the `set6` object?
I would do that in the `distr6` class directly.

The clean way might be a vectorization of `set6` checks but I´m not sure how it would look like.

Regarding public/private, can make sense to put functionality in privates, but depends on the specific design (which you don´t specify above).

**Comment by RaphaelS1** [comment]
Yes so the problem is basically `set6`. So the original method was to put all checks in the super d/p/q/r/ methods, a simple one line using the support inheriting from `Set`: `support$contains(x)`. But because `set6` doesn't use C, this created a massive bottleneck. With the additional problem that most of the  externally implemented d/p/q/r already do this check so it's unnecessarily repeated. The problem is that not all externally implemented distributions do this check, and any custom distributions may not, hence the original motivation

**Comment by fkiraly** [comment]
Hm, I see two problems:
* user feedback - should there be a uniform "not in the support, dear user" return
* support checking methods, e.g., running `mydistr$support$contains(x)` should work uniformly

if we were to have some distributions doing the checks externally, some internally.

When is the bottleneck created? In `VectorDist` only or in all distributions?

**Comment by RaphaelS1** [comment]
> user feedback - should there be a uniform "not in the support, dear user" return

This is the base R approach, the problem is that this may not be obvious immediately to the user. For example (and this example would not occur in real life), say we had predicted a vector of survival distributions including Normal(0,1) and Uniform(5,10). Then user decides to evaluate the vector at pdf(1), your method would crash the vector when trying to evaluate Uniform(5,10)

> support checking methods, e.g., running mydistr$support$contains(x) should work uniformly

agreed but this can't be enforced as we can't stop internally implemented methods doing this, so we can't avoid the overlap

> When is the bottleneck created? When doing what? And in VectorDist only, or in all distributions?

it's a set6 bottleneck, which would be closed (or vastly improved) when [this](https://github.com/xoopR/set6/issues/52) is closed

**Comment by fkiraly** [comment]
>This is the base R approach, the problem is that this may not be obvious immediately to the user. For example (and this example would not occur in real life), say we had predicted a vector of survival distributions including Normal(0,1) and Uniform(5,10). Then user decides to evaluate the vector at pdf(1), your method would crash the vector when trying to evaluate Uniform(5,10)

We still have the distinction between domain and support, right? Where domain is a superset of support?

The error should be raised when the user tries to evaluate distribution defining methods outside the domain (not support, I said this incorrectly, apologies).

The user can do containedness checks for domain and support equally.
Being outside the support is ok, it just means there is no probability mass here.
Being outside the domain is a problem, because it usually means the distribution defining methods are undefined, i.e., the user instructions are ill-defined or erroneous.

>agreed but this can't be enforced as we can't stop internally implemented methods doing this, so we can't avoid the overlap

Yes, but I think it´s fine to overlap here, and even required if you adopt the strategy pattern implied by the uniform interface requirement.

>it's a set6 bottleneck, which would be closed (or vastly improved) when this is closed

Well, if you ask the maintainers of `set6` very nicely, they might take some time to hear your pleas.

**Comment by RaphaelS1** [comment]
> Being outside the domain is a problem, because it usually means the distribution defining methods are undefined, i.e., the user instructions are ill-defined or erroneous.

Hm. But then we require two checks.
e.g. imagine the scenario of discrete uniform that is defined simply as 1/N, where N is range of distribution. then we would need a support check:
* If x outside support return 0

And domain check:

* If x outside domain return error

> Yes, but I think it´s fine to overlap here, and even required if you adopt the strategy pattern implied by the uniform interface requirement.

sure

> Well, if you ask the maintainers of set6 very nicely, they might take some time to hear your pleas.

i'll give them a week

**Comment by fkiraly** [comment]
>then we would need a support check:

yes, but that happens inside the `pdf` method and is parts of its *definition* as a mathematical object, whereas the domain check is a *type check* that always happens.

One could imagine the type check being an inheritable generic, while the domain check, or whether to make one in evaluation, is up to the `pdf` and dependent on its definition. For example, for normal, you don´t need a support check.

Support and domain checks may or may not be split into different private methods.

**Comment by RaphaelS1** [comment]
Sure I see what you're saying. Okay so then we ensure distributions include support check as part of definition (i.e. anyone implementing custom distributions must adhere to this), and we include a type check that will cause error if fails. Though in line with previous discussions we will continue the rule that cdf of discrete distributions are rounded down (e.g. pbinom(0.5) = pbinom(0)) and pdfs equal zero (e.g. pbinom(0.5) = 0).
