### ISSUE TITLE
Implementing analytical log results for empirical distributions

### ISSUE THREAD

**Issue by RaphaelS1** [alan-turing-institute/distr6#193]
There are some cases where no clear analytical result can be given. For example, for the `Empirical` or `WeightedDiscrete` distributions. In this case is it better to just predict `pdf` as usual and wrap this in `log` internally. Or should we omit this and tell users to impute a numerical result with the `CoreStatistics` decorator? 

This is linked to #131

**Comment by fkiraly** [comment]
Empirical and weighted discrete distributions don't actually have a pdf (as mathematical objects) so shouldn't return one?

Or was our convention that it should be the pmf?

**Comment by RaphaelS1** [comment]
Sorry yes pmf

**Comment by fkiraly** [comment]
In that case, I don´t think we have to worry about logarithms too much then - I don´t think in practice very small weights are common (and matter much), and above they are bounded by 1 anyway?

**Comment by RaphaelS1** [comment]
excellent point
