### ISSUE TITLE
Add norms decorator

### ISSUE THREAD

**Issue by RaphaelS1** [alan-turing-institute/distr6#196]
As the final structure of this decorator is unclear, for now it would be most sensible to write these functions using S3 dispatch notation, i.e. say the function is Pdf2Norm, then this would be written as:

`<function>.<distribution>` where `<function>` is the function implemented and `<distribution>` is the classname of the distribution, see `listDistributions()` for the full list. e.g. to implement the 2-norm of Binomial pdf:

`Pdf2Norm.Binomial`

For now these can be stored in a single script for each function class, e.g. `Pdf2Norm.R`, `Cdf2Norm.R`, each containing the specific functions for each distribution.

@aintoha We will discuss here if you have any questions as you go along.

**Comment by aintoha** [comment]
So the functions should be as standard R function?

Just to confirm, for storage, all the L2norms for pdf of every distribution should be in `Pdf2Norm.R`?And same goes for `Cdf2Norm`? That means, I should not separate for different distribution?

**Comment by RaphaelS1** [comment]
Exactly

**Comment by fkiraly** [comment]
Question: if we add these as functions until the decorator is written, how should the dependency on the parameters be handled (as the methods will temporarily live outside an R6 class)?

Should these just be arguments?

**Comment by fkiraly** [comment]
based one phone discussion right now: since the function needs to call self, the signature should be `Pdf2Norm.Normal(self)` where the argument is called `self` and expects a distr object of the right type. That way, later calls to `self` from within the class follow the same syntax, and the method can be added to the decorator by simply removing the argument.

**Comment by RaphaelS1** [comment]
Sorry I didn't see this sooner Franz. After discussion with Ain it transpires that this is vastly simpler than what I initially thought and these can be added directly to the `squared2Norm` method in each Kernel but with an argument to control the shift

**Comment by fkiraly** [comment]
It would still have to be done somewhere, no?
And we sould still need it for the distributions, not just for kernels.

Though using the kernel version for the distribution may simplify things.

On a minor note, I would call the methods something more descriptive like `pdfSquared2Norm` or `pdfShiftedInnerProduct`.

**Comment by RaphaelS1** [comment]
> Though using the kernel version for the distribution may simplify things.

Exactly

> On a minor note, I would call the methods something more descriptive like pdfSquared2Norm or pdfShiftedInnerProduct.

I agree and had been thinking something similar

**Comment by RaphaelS1** [comment]
Closing as now being implemented as methods and not decorators
