### ISSUE TITLE
Add multivariate empirical distribution

### ISSUE THREAD

**Issue by RaphaelS1** [alan-turing-institute/distr6#201]
I've added a multivariate empirical distribution, primary purpose to estimate the cdf.
This has lead to some nice multivariate plotting, see below estimates for bivariate normal and multinomial.

Currently this is implemented as pdf:

mean(f1 == x1 & f2 == x2)

and cdf:

mean(f1 <= x1 & f2 <= x2)

But I'm wondering if there's no point even including the pdf as it's impossible to ever 'hit' a valid pair of points, so the plots always end up being empty.

![mvn_cdf](https://user-images.githubusercontent.com/25639974/82764793-7b5fed80-9e09-11ea-9373-61a5c13ba6c0.png)

![multinom_cdf](https://user-images.githubusercontent.com/25639974/82764789-7733d000-9e09-11ea-954d-0f2277754c9a.png)

**Comment by fkiraly** [comment]
... empirical distributions don't have a pdf? They just have a pmf.
Which brings us back to the old pdf vs pmf discussion.
(where I still think distr should have either and return the discrete/continuous parts if exists, 0 otherwise)

**Comment by RaphaelS1** [comment]
Yes and as said before, when I see 'pdf' I mean the `pdf` method. Whether that's named correctly or not is indeed still an open discussion. My preference is to defer this until after the 1.4.0 release (which will be by Friday).

My question is whether these definitions are correct though because they seem to imply an ordering that doesn't make sense in the context of distributions (yet the cdf plots look correct)

**Comment by fkiraly** [comment]
>Whether that's named correctly or not is indeed still an open discussion.

Not just about naming, but about whether there should be two methods, not just one!

>My question is whether these definitions are correct though because they seem to imply an ordering that doesn't make sense in the context of distributions

Not sure what you mean, suggest an off-line discussion.

>yet the cdf plots look correct

Well, it is a sample cdf, thus an estimate of the population cdf.

Though it doesn't look correct to me, since in the two plots the point (x,y) = (0,0) appears to be at different places.

**Comment by RaphaelS1** [comment]
>  Though it doesn't look correct to me, since in the two plots the point (x,y) = (0,0) appears to be at different places.

Don't see the problem with that... bivariate normal supported on {(a,b) : a,b in Reals}. Multinomial size 10 supported on {(a,b) : a,b in [0, 10]}

**Comment by fkiraly** [comment]
Ah, sorry, I did not read your first post properly - I thought you meant the second was an empirical sample from the normal (the first), though it is the population cdf of a multinomial considered as a bi-variate distribution over the reals.

All makes sense and looks correct, then.

**Comment by RaphaelS1** [comment]
okay great thanks!

**Comment by fkiraly** [comment]
(sorry for me misreading your post)
