### ISSUE TITLE
Permanently Constructed sets

### ISSUE THREAD

**Issue by RaphaelS1** [alan-turing-institute/distr6#221]
This may be a slight abuse of OOP but would probably help reduce bottlenecks. 

For example the Normal distribution parameter set requires one object of class `Reals` and three of class `PosReals`. Given that these objects are all identical, could we just construct all special sets once and use these as references in parameter sets? It is probably an abuse of most OOP principles but would save massively on time. Any strong opposition @fkiraly?

**Comment by RaphaelS1** [comment]
10x faster...

``` r
library(set6)
library(distr6)

pr = PosReals$new()
reals = Reals$new()
microbenchmark::microbenchmark(
  {
    ps <- ParameterSet$new(
      id = list("mean", "var", "sd", "prec"),
      value = list(0, 1, 1, 1),
      support = list(Reals$new(), PosReals$new(), PosReals$new(), PosReals$new()),
      description = list(
        "Mean - Location Parameter",
        "Variance - Squared Scale Parameter",
        "Standard Deviation - Scale Parameter",
        "Precision - Inverse Squared Scale Parameter"
      )
    )
  },
  {
    ps <- ParameterSet$new(
      id = list("mean", "var", "sd", "prec"),
      value = list(0, 1, 1, 1),
      support = list(reals, pr, pr, pr),
      description = list(
        "Mean - Location Parameter",
        "Variance - Squared Scale Parameter",
        "Standard Deviation - Scale Parameter",
        "Precision - Inverse Squared Scale Parameter"
      )
    )
  }
)
#> Unit: milliseconds
#>                                                                                                                                                                                                                                                                                                                                                                                                     expr
#>  {     ps <- ParameterSet$new(id = list("mean", "var", "sd", "prec"),          value = list(0, 1, 1, 1), support = list(Reals$new(),              PosReals$new(), PosReals$new(), PosReals$new()),          description = list("Mean - Location Parameter", "Variance - Squared Scale Parameter",              "Standard Deviation - Scale Parameter", "Precision - Inverse Squared Scale Parameter")) }
#>                                        {     ps <- ParameterSet$new(id = list("mean", "var", "sd", "prec"),          value = list(0, 1, 1, 1), support = list(reals, pr, pr,              pr), description = list("Mean - Location Parameter",              "Variance - Squared Scale Parameter", "Standard Deviation - Scale Parameter",              "Precision - Inverse Squared Scale Parameter")) }
#>       min       lq      mean    median        uq      max neval cld
#>  7.837570 8.646294 11.829349 10.037272 12.679188 31.01969   100   b
#>  1.262013 1.359536  1.828612  1.518905  1.807844 18.46455   100  a
```

<sup>Created on 2020-07-28 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by RaphaelS1** [comment]
I've found a good compromise. Using the same object for distribution types is a bad idea because these get composed and may not be properly cloned thus leading to problems throughout the package but using these objects only in parameter sets is justified as no composition or manipulation happens on this level

**Comment by fkiraly** [comment]
>Any strong opposition @fkiraly?

Yes, that´s what I wanted to say - pass-by-reference vs pass-by-value might be a problem if it is the same object.
*however*, it´s not an anti-oop pattern - the "singleton" pattern (only one object of a kind can exist) is an actual gang of four pattern. Haven´t seen it used for "constants" as you are thinking, though.

**Comment by RaphaelS1** [comment]
Thanks. In which case I might try it out in parametersets as it does result in a big speed-up and doesn't break any builds. Isn't difficult to change back after. Though I think including it for parameter domains is a bad idea due to composition problems.
