### ISSUE TITLE
Add kernel methods

### ISSUE THREAD

**Issue by RaphaelS1** [alan-turing-institute/distr6#226]
@aintoha let's use this issue to discuss everything related to your kernel methods now.
Can you please let me know here:

1. What methods you are implementing?
2. What tests have been added?
3. What currently needs to be reviewed?
4. What work is left to do?

@fkiraly

**Comment by aintoha** [comment]
The ones I updated on `cpp_kernel` branch 
1. L2norm for kernel for 
i. integrals with lower bound= -infinity to upper bound = infinity
ii. integrals with lower bound= -infinity to upper bound = upper 
2. Numerical test 
i. for the upper bound = upper
3. The test should be reviewed 
4. You mention that we have to the analytical test for the L2norm of the pdf and add the L2norm of the cdf and the L2norm of (1 - cdf) for the kernels

**Comment by RaphaelS1** [comment]
> L2norm for kernel for
i. integrals with lower bound= -infinity to upper bound = infinity
ii. integrals with lower bound= -infinity to upper bound = upper
Numerical test
i. for the upper bound = upper

Thanks these are passing so I think are complete.

> You mention that we have to the analytical test for the L2norm of the pdf and add the L2norm of the cdf and the L2norm of (1 - cdf) for the kernels

Have you implemented L2norm of cdf?

**Comment by aintoha** [comment]
I have done for uniform, epanechnikov, quartic and triangular kernels. I've done them like this. 
The L2norm of the cdf and the L2norm of (1-cdf) are connected where I call the negative input of L2norm cdf. Example
`cdfSquared2Norm(x, upper)` then `cdfSquared2NormInv(x, lower) = cdfSquared2Norm(x = -x, lower = -upper)`. 
The functions are long and have many conditions, so I use functions inside a function then use the `if esle`. This is similar to `pdf2SquaredNorm` for Tricube. 
Not all kernels will have `cdfSquared2NormInv`, eg: Sigmoid and Logistic kernel.
Later on, the brier score will call both `cdfSquared2Norm(x, upper)`  and `cdfSquared2NormInv(x, upper)`. 

So, right now, I'm wondering where in the kernel should we input the `cdfSquared2Norm()` and `cdfSquared2Norm()`?

**Comment by RaphaelS1** [comment]
> cdfSquared2NormInv(x, lower) = cdfSquared2Norm(x = -x, lower = -upper)

What does this function do? And what is the point of it, i.e. does it have such a well-used use-case that someone couldn't use `cdfSquared2Norm` instead? 

> So, right now, I'm wondering where in the kernel should we input the cdfSquared2Norm() and cdfSquared2Norm()?

Exact same as `pdfSquared2Norm`!

**Comment by aintoha** [comment]
> What does this function do? And what is the point of it, i.e. does it have such a well-used use-case that someone couldn't use `cdfSquared2Norm` instead?

This is for the Integrated Brier Loss, 
`IBL = cdfSquared2Norm + cdfSquared2NormInv`

**Comment by RaphaelS1** [comment]
> This is for the Integrated Brier Loss,
IBL = cdfSquared2Norm + cdfSquared2NormInv

I think it makes more sense to just use `cdfSquared2Norm` and manually make the adjustments. Otherwise you'll have to include the method, documentation, and tests for all kernels and it's unlikely to be used for vast majority of people.

> Ok, I see it now.

Please also add tests in the same way

**Comment by aintoha** [comment]
> > This is for the Integrated Brier Loss,
> > IBL = cdfSquared2Norm + cdfSquared2NormInv
> 
> I think it makes more sense to just use `cdfSquared2Norm` and manually make the adjustments. Otherwise you'll have to include the method, documentation, and tests for all kernels and it's unlikely to be used for vast majority of people.

I'm not sure we can do it like that, because there are conditions `cdfSquared2NormInv(x, lower)` will be equal to  `cdfSquared2Norm(x, upper)`. I'll add the quartic kernel first and see if it can be simplifies when calling the brier loss

**Comment by aintoha** [comment]
Okay, I added both `cdfSquared2NormInv(x, lower)` and `cdfSquared2Norm(x, upper)` for Quartic

**Comment by RaphaelS1** [comment]
> I'm not sure we can do it like that, because there are conditions cdfSquared2NormInv(x, lower) will be equal to cdfSquared2Norm(x, upper).

I don't understand, from your definition: `cdfSquared2NormInv(x, lower) = cdfSquared2Norm(x = -x, lower = -upper)`

Is this not always the case?

**Comment by aintoha** [comment]
sorry, I thought it will turn out differently. 


I will only add the `cdfSquared2Norm` then.

**Comment by aintoha** [comment]
I added the cdfSquared2Norms for all except for (Normal, Sigmoid and Logistic). I change the input of the `cdfSquared2Norm(x = 0, upper = inf)` to  `cdfSquared2Norm(x = 0, upper = 0)` because  if the default of `upper` is infinity then the whole function will be infinity. But this will come out as error when I am doing the numerical test for `upper`. For example is the Epanechnikov  kernel testthat file.

**Comment by RaphaelS1** [comment]
Thanks all looks good and all tests passing.
Quick question, for Silverman I couldn't find/derive a closed-form expression for cdf, but you have a function for cdfsquared2norm. So,i) is there an expression for cdf? ii) is your implementation for cdfsquared2norm an analytic closed-form expression?

**Comment by aintoha** [comment]
Okay, so I will add the numerical test for upper for all kernels then. 
I think it should have a cdf but i derive the close-form and use that for cdfSquared2Norm.

**Comment by aintoha** [comment]
There is an issue with Tricube kernel. It can't run for a vector and only one at a time.

**Comment by RaphaelS1** [comment]
Don't worry I've done the numeric tests. I'll look at tricube shortly

**Comment by RaphaelS1** [comment]
For tricube I cannot fix this for you unfortunately. The code is too complex for me to read and I am unable to debug it. I think you're going to have to try and step through the function manually yourself to find where the bug is. I suggest doing this by looking at f1-f8 separately.

**Comment by RaphaelS1** [comment]
@aintoha how's this going?

**Comment by aintoha** [comment]
Hi,

sorry, I didn't notice this. Is it better to leave it out for now? i doubt people will use Tricube kernel.

Regards,
Ain
________________________________

**Comment by RaphaelS1** [comment]
I don't think it's a great idea to have code in there that doesn't work and deleting it would be a shame because it probably only needs a small amount of work to fix it. I could merge in everything else and leave it out with an open issue

**Comment by aintoha** [comment]
That is good idea.  My prioritize now is to solve for Gaussian kernel because that is more important. But once that is settle, I will get back to Tricube.

Thanks
________________________________

**Comment by aintoha** [comment]
So,  these are kernels that have issues for L2norm cdf
1. Gaussian  - issue: cannot compute integral 
2. Tricube, - issue: code issue 
3. Logistic  - issue: cannot compute integral 
4. Sigmoid  - issue: cannot compute integral

**Comment by RaphaelS1** [comment]
> Logistic - issue: cannot compute integral - divergent
Sigmoid - issue: cannot compute integral - divergent

This is not an issue, just don't include the method and we add a line to the documentation saying it isn't included because it's divergent.

> Gaussian - issue: cannot compute integral

Because it's also divergent?

**Comment by aintoha** [comment]
the integral for gaussian is leads to infinity. There is a way to do it but not using cdfsquared2norm but using expectation method.

**Comment by aintoha** [comment]
I add the logistic kernel and it should be fine. But there is an issue with the Tricube. I fix the function but there is an error in the test-that. The error is below: 

`test-KernelTricube.R:4: failure: autotest
formals(kern$public_methods$cdfSquared2Norm) not equal to pairlist(x = 0, upper = Inf).
Component "upper": Mean absolute difference: Inf

test-KernelTricube.R:30: error: cdfsquared2norm upper
non-numeric argument to mathematical function
Backtrace:
 1. expect_rounded_equal(...) C:UsersAin TohaDropboxdistr6teststestthattest-KernelTricube.R:30:2
 5. kern$cdfPNorm(2, upper = 2)
 6. distr6::generalPNorm(self$cdf, p, lower, upper) C:UsersAin TohaDropboxdistr6RDistributionDecorator_ExoticStatistics.R:114:8
 7. stats::integrate(f = function(x) abs(fun(x))^p, lower, upper) C:UsersAin TohaDropboxdistr6RgeneralPNorm.R:23:2
 9. distr6:::f(x, ...)`

**Comment by RaphaelS1** [comment]
Summarising our call: delete methods cdfsquared2Norm for Gaussian, Logistic and Sigmoid. Add cdf method for tricube. Then all tests should pass and we can merge to master.

**Comment by aintoha** [comment]
There is an error when running testthat for Tricube. The error is due to the cdfsquared2Norm. So, I wondering how does distr6 actual call cdfPNorm and pdf2Norm?

**Comment by RaphaelS1** [comment]
It would be very helpful if you could share the error

**Comment by aintoha** [comment]
It's a failure error on the test that comes out as 

test-KernelTricube.R:31: failure: cdfsquared2norm upper
kern$cdfPNorm(2, upper = 2)^2 not equal to kern$cdfSquared2Norm(upper = 2).
1/1 mismatches
[1] 1.79 - 1.78 == 0.0102

test-KernelTricube.R:32: failure: cdfsquared2norm upper
kern$cdfPNorm(2, upper = 0)^2 not equal to kern$cdfSquared2Norm(upper = 0).
1/1 mismatches
[1] 0.0603 - 0.0501 == 0.0102

**Comment by RaphaelS1** [comment]
These tests aren't essential, I've just commented them out for this. Is that everything now?

**Comment by aintoha** [comment]
Yes, that's all. Thank you

**Comment by RaphaelS1** [comment]
Okay so is the kernel branch now ready to merge into master?

**Comment by aintoha** [comment]
Yes, you can merge them now. Thank you
