### ISSUE TITLE
kthmoment do no work

### ISSUE THREAD

**Issue by mteixi** [alan-turing-institute/distr6#231]
> G = Gumbel$new()
> kthmoment(G, k = 2, type = "raw")
Error in do.call(get("object")[["kthmoment"]], args) : 
  'what' must be a function or character string

> sessionInfo()
R version 4.0.2 (2020-06-22)
Platform: x86_64-apple-darwin17.0 (64-bit)
Running under: macOS Catalina 10.15.6

Matrix products: default
BLAS:   /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/4.0/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] distr6_1.4.4

loaded via a namespace (and not attached):
 [1] compiler_4.0.2    backports_1.1.10  R6_2.4.1          set6_0.1.8       
 [5] tools_4.0.2       Rcpp_1.0.5        data.table_1.13.0 checkmate_2.0.0  
 [9] R62S3_1.4.1       extraDistr_1.9.1  pracma_2.2.9

**Comment by RaphaelS1** [comment]
Hi, you `kthmoment` requires the `CoreStatistics` decorator. Please try the following:

```R
G = Gumbel$new(decorators = "CoreStatistics")
kthmoment(G, k = 2, type = "raw")
```

**Comment by mteixi** [comment]
Thanks, it works

**Comment by fkiraly** [comment]
@RaphaelS1, random thought - is it "breaking the pattern", or would it make sense considering loading decorators on the fly? I.e., objects replacing themselves with decorated instances, if a user doesn´t do the decoration themselves? Potential source of inefficiency (and may warrant a warning), but avoiding the above kind of user frustration.

**Comment by RaphaelS1** [comment]
I don't know how this would work but also don't think it's warranted. Arguably the above function and `genExp` could be moved to `ExoticStatistics` as they're the only methods in Core that don't numerically estimate missing results.

**Comment by fkiraly** [comment]
>I don't know how this would work

* singleton or global lookup table for decorater name, given method name
* when calling object with an unknown method, uses lookup table to find decorator
* if exists, object replaces itself with decorated instance - re-constructed or via state/parameter pass-on - and raises warning

Not sure whether it´s worth the effort though

> but also don't think it's warranted

You´re probably right?

**Comment by RaphaelS1** [comment]
That would also mean an overhaul of R6, which we seem to come back to again and again....
