### ISSUE TITLE
Add kernel bw parameter

### ISSUE THREAD

**Issue by RaphaelS1** [alan-turing-institute/distr6#235]
@fkiraly @aintoha use this issue to discuss adding a `bw` parameter for bandwidth to kernels.

**Comment by aintoha** [comment]
I added parameter (bw) in the initialize  for `NormalKernel' but there is error 

`Error in UseMethod("getParameterSet", object) : 
  no applicable method for 'getParameterSet' applied to an object of class "c('NormalKernel', 'Kernel', 'Distribution', 'R6')" '

**Comment by RaphaelS1** [comment]
Yes you need to update https://github.com/alan-turing-institute/distr6/blob/master/R/getParameterSet.R.

Sorry I need to update the extension guidelines to make this all clearer. As you're only adding one parameter I'd recommend looking at `getParameterSet.ChiSquared` as an example and this file: https://github.com/alan-turing-institute/distr6/blob/master/R/SDistribution_ChiSquared.R

**Comment by aintoha** [comment]
@RaphaelS1  I updated for `NormalKernel' tp the branch 'kernel_bandwidth`. I added the parameter in the `pdfSquared2norm` and `cdf'.  I also added other method. Can you please take a look it before I start making the same changed to other kernels?

**Comment by RaphaelS1** [comment]
Where have you stored the `getParameterSet` dispatch method for `NormalKernel`?

**Comment by aintoha** [comment]
Sorry, I forgot to push that files. It's in https://github.com/alan-turing-institute/distr6/blob/kernel_bandwidth/R/getParameterSet.R 

I updated the other kernels as well.

**Comment by RaphaelS1** [comment]
> Sorry, I forgot to push that files. It's in https://github.com/alan-turing-institute/distr6/blob/kernel_bandwidth/R/getParameterSet.R

Thanks, this looks good but there's a typo in the `description` field.

> Can you please take a look it before I start making the same changed to other kernels?

I've only looked at `NormalKernel` and I can see that `super$initialize()` is missing, this must be the last line in the constructor for all kernels.

I haven't looked at the individual methods, as I think you know how to pull parameters. Can you please make sure you have unit tests that cover different bandwidth options?

**Comment by aintoha** [comment]
@RaphaelS1 I remove the `super$initialize()`  because when I include it, it does not detect the bw as a parameter. 

> normkern <- NormalKernel$new(bw = 0.1)
> normkern
Norm()

**Comment by RaphaelS1** [comment]
Please delete line 30 from `Distribution_Kernel.R` and re-add `super$initialize()`

**Comment by RaphaelS1** [comment]
At the same time please check if there's anything else in the constructor of Distribution_Kernel that needs to be changed or removed, e.g. kernel support

**Comment by aintoha** [comment]
@RaphaelS1 thanks, I removed line 30 in `Distribution_Kernel.R' 

But I didn't change the pdf and cdf of each kernel because they all called from C

**Comment by RaphaelS1** [comment]
@aintoha can you take a look at the files in C and see if you can understand them at all?
If not don't worry about it but you may find that they actually look very similar to R

https://github.com/alan-turing-institute/distr6/blob/kernel_bandwidth/src/Kernels.cpp

**Comment by aintoha** [comment]
@RaphaelS1 I did look into the C file and edit for Normal kernel, add the parameter and the output is a matrix. Let me know if that is okay. Then, I can change for others.

**Comment by RaphaelS1** [comment]
@aintoha really great first attempt, I haven't checked if it compiles but it looks good to me, except that you need to change the first line: `NumericVector C_NormalKernelPdf` to `NumericMatrix C_NormalKernelPdf`.

For code in C it's really important you try to compile it locally first because it's easy to make very small mistakes (like missing a semi-colon) that cause 'fatal errors'. To do this you can just run `devtools::document()` or `devtools::load_all()` like normal.

And as normal please make sure you add unit-tests

**Comment by aintoha** [comment]
@RaphaelS1 I changed the `NumericVector C_NormalKernelPdf to NumericMatrix C_NormalKernelPdf'. By compiling it locally, you mean just run the `devtools::load_all()`.  I ran that line and test the function. The output is what I expected. 

I ran the testthat for the Normalkernel but there is an error:

Loading distr6

== Testing test_kernel_normal.R ================================================
[ FAIL 1 | WARN 0 | SKIP 0 | PASS 34 ]

-- Failure (test_kernel_normal.R:2:3): autotest --------------------------------
kern$strprint() not equal to paste0(shortname, "()").
1/1 mismatches
x[1]: "Norm(bw = 1)"
y[1]: "Norm()"

[ FAIL 1 | WARN 0 | SKIP 0 | PASS 34 ]

Test complete

I think I should change something here, but I don't know where.

**Comment by RaphaelS1** [comment]
> By compiling it locally, you mean just run the devtools::load_all()`. I ran that line and test the function. The output is what I expected.

Great!

> I think I should change something here, but I don't know where.

So the error here is in the autotest which I set to assume no parameters. Basically we just need to decide what the default `bw` value should be for all kernels that have this parameter, then I can update the test to reflect this

**Comment by aintoha** [comment]
> So the error here is in the autotest which I set to assume no parameters. Basically we just need to decide what the default `bw` value should be for all kernels that have this parameter, then I can update the test to reflect this


I have set the default to `bw = 1`. I think that is appropriate so that user can get the original kernel without the bandwidth.

**Comment by RaphaelS1** [comment]
Okay I've updated the autotest. Can you please make sure all kernels, even the ones whose bandwidth you haven't changed, have `bw = 1` in the initialize function?

Then for any kernel where you aren't changing the bandwidth from 1, make sure the parameterset has the support `Set$new(1)` for the `bw` parameter

**Comment by aintoha** [comment]
@RaphaelS1 I changed all pdf and cdf for each kernel. The only thing I did not change is the quantile functions. I also add the `cdfIntegral`, `ccdfIntegral` and `energyBrier` to NormalKernel. 

But, I still get the same error for the autotest (when running the autotest on LogisticKernel)

**Comment by aintoha** [comment]
@RaphaelS1 
I have a few questions, 
1. Firstly, there was still an error when I run the autotest on distr6. The error is 

Loading distr6

== Testing test_kernel_logistic.R ==============================================
[ FAIL 2 | WARN 0 | SKIP 0 | PASS 40 ]

-- Failure (test_kernel_logistic.R:2:3): autotest ------------------------------
formals(kern$public_methods$initialize) not equal to pairlist(bw = 1).
Names: 1 string mismatch
Length mismatch: comparison on first 1 components
Component 1: target is NULL, current is numeric

-- Failure (test_kernel_logistic.R:2:3): autotest ------------------------------
kern$strprint() not equal to paste0(shortname, "()").
1/1 mismatches
x[1]: "Logis(bw = 1)"
y[1]: "Logis()"

[ FAIL 2 | WARN 0 | SKIP 0 | PASS 40 ]

Test complete

So I changed a few things in the helpers.R file inside the testthat folder. 
I pushed the changes to GitHub. There's no error when I run autotest (except for NormalKernel). But let me know if that is the right way.

2. In the testthat for each kernel, what is the support​' for?

3. I added cdfIntegral, ccdfIngetral and energyBrier to NormalKernel. How should I add the unit test?

**Comment by RaphaelS1** [comment]
Further to conversations offline. We won't merge this branch as it is so you just make sure the functions work to your satisfaction either by manually testing them or adding unit tests, then we can plan better in the future.
