### ISSUE TITLE
Split package interface 

### ISSUE THREAD

**Issue by RaphaelS1** [alan-turing-institute/distr6#242]
I'm considering splitting the package interface into:

* distr6: Core package interface. Includes:
  * All abstract classes and parents.
  * Flexible distributions such as WeightedDiscrete and Categorical
  * One common continuous (Norm), discrete (Binom) and multivar (MVN) for testing + Epan kernel. 
* distribution6/distr6butions: Implemented SDistributions and kernels

First suggested to me by @aintoha and since by others. Mlr3/extralearners shows this works well and is understood by users. 

Motivation: distr6 (core) would provide a much more lightweight interface with no Suggests and will suit needs of modelling and custom distributions. It may also make contributing and organisation simpler

@fkiraly thoughts?

**Comment by fkiraly** [comment]
Im teresting suggestion.
Though, could you kindly explain what would be the benefit of this?

For `mlr3` I see how it makes sense, since it's a larger ecosystem and users may not want to load all parts of it for their needs.
For `distr6`, what would be the "common case" in which users may want to load one package and not the other? Or is there another reason for suggesting a split?

**Comment by RaphaelS1** [comment]
Two primary reasons and one smaller one:

1. distr6 is a large package but CRAN standards, i.e. we always get the NOTE our package is larger than expected, which is fine because this is a known side effect of Rcpp. However it does highlight a lot of extra bulk comes with distr6: compiled code, a long list of suggested packages (longer package checks on GH and CRAN) and maybe some dependencies that could otherwise be avoided. Separation allows a very lightweight core.
2. Following on from 1) the core would still be powerful. We have both discussed (together and with others) how distr6 could provide a powerful sampling interface (e.g. of parameters). Currently the added bulk can be off-putting as a dependency (this has been said to me before). Including the flexible distributions above in core allows this sort of sampling as well as more complex compositions.
3. Minor point but it would make development and maintenance slightly easier, i.e. we wouldn't need to worry about package breaks due to one distribution dependency (though most of these are internal anyway), and it could make updates and contributions more straightforward, e.g. direct contributors towards the more 'interesting' design and development of numerical/analytic features and not the more standardised creation of distributions

**Comment by RaphaelS1** [comment]
Another reason for splitting: Cpp compile times are very long.
