### ISSUE TITLE
Hypergeometric distribution

### ISSUE THREAD

**Issue by stamats** [alan-turing-institute/distr6#258]
With the newest version (1.6.0) of distr6 
Hypergeometric$new(size = 500L, successes = 5L, draws = 20L)

gives

Error in assert_named_list(x, types = private$.types) : 
  'x' must have unique name

The same happens with
X6$setParameterValue(size = 500)

Best Matthias

**Comment by RaphaelS1** [comment]
Thanks Matthias! (and happy to see you using distr6!)
Closed in #259
