### ISSUE TITLE
Unstated R>=4.0.0 dependency

### ISSUE THREAD

**Issue by MichaelChirico** [alan-turing-institute/distr6#264]
https://github.com/alan-turing-institute/distr6/blob/d75e303873080ebe6a72d0bef15df6d570b501e5/R/Wrapper_VectorDistribution.R#L244-L247

This test assumes `stringsAsFactors = FALSE` by default:

https://github.com/alan-turing-institute/distr6/blob/d75e303873080ebe6a72d0bef15df6d570b501e5/tests/testthat/test-asDistribution.R#L15

Otherwise the value there is a `factor`.

There are a few possible fixes:

 1. Just use `data.table()` to construct the object
 2. Supply an explicit value of `stringsAsFactors` to the `data.frame()` call
 3. Use `as.character()` on the LHS of the test
 4. Add an R>=4.0.0 dependency to the package

Happy to file a PR in whichever direction is best for you.

**Comment by RaphaelS1** [comment]
Hey good catch. My gut is to add the dependency but I'll just patch the test so people using R<4 can use this package for a bit longer...
