### ISSUE TITLE
Implement parser function

### ISSUE THREAD

**Issue by RaphaelS1** [alan-turing-institute/distr6#277]
https://twitter.com/CatchTwentyToo/status/1546509861432729600

```R
x <- distr6_parse("N(10, 100)")
# x is equivalent to Normal$new(mean = 10, var = 100)
```

**Comment by RaphaelS1** [comment]
I see the benefit in the idea and I see the 'easy' way to implement which would be something like below (but with a bunch of validators). However this requires someone knowing all distr6 distribution names. Or not being able to use things like you said above, e.g. 'N' for Normal or 'U' for uniform'

``` r
library(distr6)
dparse <- function(str) {
  d <- gsub("(\\w+)\\(([0-9A-Za-z, ]+)\\)$", "\\1", str)
  p <- gsub("(\\w+)\\(([0-9A-Za-z, ]+)\\)$", "\\2", str)
  dstr(d, pars = as.list(as.numeric(strsplit(p, ", ")[[1]])))
}

dparse("Norm(0, 1)")
#> Norm(mean = 0, var = 1)
```

<sup>Created on 2022-07-11 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>
  ###

**Comment by RaphaelS1** [comment]
Maybe if you tell me your use-case in more detail we can figure out the best implementation. (Looks weird me talking to myself here)

**Comment by brockk** [comment]
Hi Raphael, sorry for the delay (life gets in the way!).

My use case is a Shiny app. Users can specify their prior beliefs and these are then used in an analysis. Of course, many distributions could be specified by the user (and distr6 supports them all). One way of getting the prior params (and the method I will probably use) is to have a drop down for distribution name (normal, gamma, t, etc), and then inputs that react to dist name for mean, sd, rate, shape (etc). Using a similar method I could also build in truncation and mixtures. However a text field take expects things like:
“norm(0, 1)” 
or “gamma(2, 0.1)” 
or “0.7 * norm(0, 1) + 0.3 * gamma(2, 0.1)”
removes the need for a lot of fiddly inputs.

**Comment by brockk** [comment]
And that would require a parser function.

This is just an idea I had when I was sketching out how our shiny app layout would look. 

Loving distr6. Thanks for creating it

**Comment by RaphaelS1** [comment]
Cool I get the idea, fully agree that free text is the easier way to go however I think a drop-down might be simpler. I see the appeal of the above method as it allows a lot of cool ways of combining distributions but it does mean users know the required distribution names/abbreviations so I'm hesitant to implement something that actually may require *more* work from the user. But if you really think this will add to your use-case then I'd propose something like creating a field for distributions called something like `aka` and this would include all possible namings, then the parser would use this to look-up the require distribution from the name.

e.g. (pseudo-code won't work)
```R
> Normal$aka
[1] "Normal" "normal" "N" "norm" "Norm"

distr_lookup <- function(str) {
 ds <- list_distributions()
 ds[grepl(d, ds$aka), "ClassName"]
}

dparse <- function(str) {
  d <- distr_lookup(gsub("(\\w+)\\(([0-9A-Za-z, ]+)\\)$", "\\1", str))
  p <- gsub("(\\w+)\\(([0-9A-Za-z, ]+)\\)$", "\\2", str)
  dstr(d, pars = as.list(as.numeric(strsplit(p, ", ")[[1]])))
}

> dparse("Norm(0, 1)")
Norm(mean = 0, var = 1) 
```

Let me know your thoughts

**Comment by RaphaelS1** [comment]
If you like the idea then would appreciate help in the form of a few PRs to add the `aka` method. I can code the lookup and parser relatively quickly based on the above.

**Comment by RaphaelS1** [comment]
Hi @MichalLauer, thanks for this! I'm not super keen on a whole other package as that would be put too much on the devs and not the user, at some point people have to put in a *little* bit more effort than expect the function to do everything.
So in the top example with "N(0, 1)" this would result in the default parametrisation but for anything else we should expect something like "N(mean = 0, sd = 1)". I think adding the `aka` field is probably the most we can do to help the user.

What do you think? Let me know if you disagree!

**Comment by fkiraly** [comment]
@MichalLauer, I think actually yours is a great idea.

I have in fact implemented something very similar recently for `sktime`, released in 0.20.1, it is a generic text-to-composite-object functionality that works in general (distributions, estimators, etc) - in python though.

See here:
https://github.com/sktime/sktime/pull/4738

I do think this also makes a lot of sense for the `mlr3` ecosystem!
(in the python scikit space, it would eventually live in `scikit-base`).

Happy to work with you to implement this idea in R and add it to the r6-verse if you'de like!

**Comment by fkiraly** [comment]
PS: in my opinion, the trick would be smart alias parsing, without throwing too much regexes at the problem.

**Comment by RaphaelS1** [comment]
@MichalLauer  I've combined our solutions into the following, let me know your thoughts

``` r
library(distr6)

ds <- listDistributions()
# add a dummy column for now
ds$aka <- as.list(runif(nrow(ds)))
# in practice we'd add these to all distributions in their files
ds[ClassName == "Normal", aka := c("Normal", "N", "Norm")]

dparse <- function(str) {
  # get everything before '('
  distr = gsub("(^(.*))\\(.*", "\\1", str)
  # match to distribution list
  distr = ds[grepl(tolower(distr), tolower(aka)), ClassName]
  # get everything within '()'
  params = gsub("[^(]*\\(([^)]*)\\)[^)]*", "\\1", str)
  # create the call
  call <- sprintf("distr6::%s$new(%s)", distr, params)
  # evaluate
  eval(parse(text = call))
}

dparse("Norm(0, 1)")
#> Norm(mean = 0, var = 1)
dparse("Norm(0, sd = 1)")
#> Norm(mean = 0, sd = 1)
dparse("normal(sd = 1, mean = 2)")
#> Norm(mean = 2, sd = 1)
dparse("N(var = 1, sd = 2)") # errors as expected
#> Error in .return_fail(msg = "Multiple linked parameters are set.", error_on_fail): Multiple linked parameters are set.
dparse("n(var = 1, mean = 3)")
#> Norm(mean = 3, var = 1)
```

<sup>Created on 2023-07-16 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by MichalLauer** [comment]
Hello @RaphaelS1,

Looks good to me. I will fork this repo and start implementing stuff.
One question that comes to my mind is about *aka* - is it an acronym for something or just a dummy placeholder?

**Comment by RaphaelS1** [comment]
Amazing thanks!

Aka = also known as. Could also use `aliases` to be more in line with R terminology.

**Comment by RaphaelS1** [comment]
One thing to think about for implementation: We'd need to think about suitable aliases for all distributions (though could definitely start with just the full name and shortname) so you'd want the lookup not just to check the `aka` (or whatever you call it) column but also the full name and shortname columns.

**Comment by MichalLauer** [comment]
Yes, I thought about that.

I added a column 'Shortcuts' to the `listDistributions()`, which is really just a shortcut of the distribution (Normal -> N, Lognormal -> LN...). The lookup will then happen using *ShortName*, *ClassName*, and this new *Shortcut*.

The only update I did though is to .distr6  in *distr6-globals.R* , e.g.:

```r
...
.distr6$distributions <- data.table(
  ShortName = NULL, ClassName = NULL, Type = NULL,
  ValueSupport = NULL, VariateForm = NULL, Package = NULL,
  Tags = NULL, Alias = NULL
)
...
```

I will look into the aliases as well.
No worries, happy to help as I use this package quite often :)

**Comment by MichalLauer** [comment]
Please let me know if anything needs to be changed or updated. Apologies for any potential "easy" mistakes, as this is one of my first contributions to open source:)

**Comment by RaphaelS1** [comment]
> Apologies for any potential "easy" mistakes, as this is one of my first contributions to open source:)

Don't apologise! Everyone starts somewhere. Happy to point out other 'good first issues' in distr6 once this PR is closed if you want to contribute more

**Comment by MichalLauer** [comment]
I would be happy to help with more issues; I should have some free time on my hands right now:)

I am ready to create another pull request with recommended changes and updates to NEWS, DESCRIPTION, etc. Is there a recommended list of commands from the `{devtools}` package I should run on my machine before pushing?

**Comment by RaphaelS1** [comment]
Nah, just document etc.
If useful we can call to discuss issues you could work on?  Happy to give some pointers and help if useful.
I'll also go through issues now and mark "good first issues"
Thanks so much!

**Comment by MichalLauer** [comment]
Thank you for the offer, but at the moment, I'd prefer to communicate through GitHub comments and continue working on the issues marked as 'good first issues'. I prefer learning and researching at my own pace :)
