### ISSUE TITLE
Code of Conduct incident note and remedial order - raphaels1, please remedy unauthorized removal of fkiraly, deletion of messages

### ISSUE THREAD

**Issue by fkiraly** [alan-turing-institute/distr6#290]
@raphaels1, this is to let you know that I consider your behaviour a serious violation of the `distr6` code of conduct. You are to remedy your actions immediately. I have decided that this public statement is appropriate and necessary, to keep this matter transparently in the public record and to allow you to react.

* you did the below without any consent, communication or justification whatsoever.
* you removed my admin access to this repository, despite me being an owner, the intellectual originator of the project, providing much of the original designs, project management, and funding for it (e.g., for the 2018-2019 UCL student projects which implemented most of the distributions). I am also a member of formal governance bodies of the project according to its current documentation and the documentation at the time.
* you ignored and then deliberately deleted my request to restore my admin access here: https://github.com/alan-turing-institute/distr6/issues/287
* you deleted perfectly reasonable contributions to a technical discussion with @MichalLauer in this thread https://github.com/alan-turing-institute/distr6/issues/277 - to the effect of silencing me, and, worse, making me appear as if I had said something inappropriate.

You have carried out multiple actions, which in the balance of probabilities can only be explained as deliberate, intentional, and premeditated. You have also had 3 months of time to react to my requests of remedial, which have elapsed without any action or communication on your side.

You are therefore in violation of the `distr6` code of conduct and must take the following actions for remedial immediately:

* restore my admin access to this repository
* publicly apologize on issue #277 for the unjustified deletion of my messages, pinging all participants of the thread with your apology
* restore any of my messages you deleted from this repository to their original state

If you fail to take these actions or ignore (or delete) this notice, your violations of the `distr6` code of conduct will compound, which can lead to more severe penalties.

**Comment by MichalLauer** [comment]
Hello both,

I'm really confused by these messages and behavior. @RaphaelS1, could you please shed some light on what is happening and why are @fkiraly's messages and posts removed?

I find this package really helpful in my personal and academic work and it would be a shame if others couldn't use it and contribute in the future. This misunderstanding could bring down the whole `{distr6}` ecosystem and could discourage a lot of people who work/would work on this. Not clearing this issue will discourage (me included) a lot of other contributors.

Looking forward to clearing this up.

**Comment by RaphaelS1** [comment]
Hi @MichalLauer , Franz has harassed me and others for several years and has been told legal action will be brought against him if further acts are made against me (or the others). This goes back several years and has already affected people's careers. He will be reported to GitHub and legal action will be carried out, I strongly advise you do not interact with this further.
