### ISSUE TITLE
Change pdf/cdf names

### ISSUE THREAD

**Issue by RaphaelS1** [alan-turing-institute/distr6#43]
As most methods are not abbreviations but full names, it might be more in line to rename as follows: `pdf -> density` and `cdf -> cumulative` this has the added benefit that defining `pdf` as an S3 generic doesn't mask the `grDevices::pdf` function.

**Comment by fkiraly** [comment]
but, unfortunately, ```density''' is already an S3 generic in stats
https://www.rdocumentation.org/packages/stats/versions/3.6.0/topics/density

An alternative would be to don't override generics but create dispatch versions that are specific to the R6 class, such as pdf.distribution ? Not sure how easy it is to do though with ```R62S3''' ...

**Comment by RaphaelS1** [comment]
The way `R62S3` works is that it first sees if a function is a generic, if it is then it defines `pdf.Distribution` otherwise it defines that and the generic `pdf`. However it is problematic in the case of `pdf` which is a function but not a generic, therefore defining the generic `pdf` masks the function pdf! However in the case of `density`, this IS a generic already, therefore `R62S3` only needs to define `density.Distribution`

**Comment by fkiraly** [comment]
A possible solution to the dilemma is a different standard behaviour of `R62S3`:

1. if a generic does not exist, define a generic (no content except dispatch)
2. always define the class-specific dispatch version

Wouldn't that solve the issue?

**Comment by fkiraly** [comment]
... or does `grDevices::pdf` not dispatch?

**Comment by RaphaelS1** [comment]
Yes this is how to R62S3 works. The problem is that when it finds that pdf exists as a function but not a generic what it doesn't do is create a new generic called `pdf` and then create `pdf.grDevices`. Of course by creating the generic `pdf` , a user can still call `grDevices::pdf` but generalising to do this may infuriate people as common functions could be accidentally masked, for example `power` and `truncate`

**Comment by fkiraly** [comment]
I'm perhaps a bit confused now.

Can you describe one situation, very explicitly, in which functions are masked, instead of new dispatch variants added?

I don't think it's a problem if `pdf(somedistribution)` defaults to the pdf of a `distr6` distribution while in all other cases `pdf` works as intended.

**Comment by RaphaelS1** [comment]
There are two options for R62S3, currently it does not give the option to pick which option to use but implements the former:
1. If `methods("someFun")` does not produce an error or warning, assume it is S3 or S4 generic. Create a dispatch version `someFun.Class` only. Otherwise create the generic `someFun` and `someFun.Class`.
1. If `methods("someFun")` does not produce an error but `isGeneric("someFun")` is `FALSE`, define the generic `someFun` and the dispatch `someFun.Class`

In the latter case, the function `someFun` is masked by the newly created generic. What's more is that when masking with a generic, the original function can only ever be accessed via `package::function`.

So now explicitly with `pdf`:
1. `R62S3` calls:
````R
x = suppressWarnings(suppressMessages((try(methods(methodname),silent=T))))
      if(class(x)!="try-error"){
        if(length(x) > 0)
````
1. Because `pdf` contains the method `pdf.options`, `R62S3` thinks that a generic exists for `pdf` therefore does not create one
1. `R62S3` creates the method `pdf.Distribution`
1. The result is that `pdf(Distribution)` has no effect as the generic doesn't exist so the specfic call `pdf.Distribution(Distribution)` must be made (which defeats the point of the generic).


Now in this particular example of pdf/cdf, by using `density` this problem is solved as there exists a generic `density`.

**Comment by RaphaelS1** [comment]
I'm closing this as masking `pdf` is less problematic than `density` and even though arguably `pdf`/`cdf` is not as clear as `density`/`distribution` I think that the former will be more familiar to most users
