### ISSUE TITLE
Vectorizing Multivariate Distributions

### ISSUE THREAD

**Issue by RaphaelS1** [alan-turing-institute/distr6#60]
There is currently a discrepancy in how multivariate distributions are designed.

By example, let `a` be an array 3 distribution implemented in distr6, to find the pdf: `a$pdf(x1 = 1, x2 = 2, x3 = 3)` - Each argument is separated.

Let `mn` be a multinomial distribution implemented in distr6, to find the pdf: `mn$pdf(1:3)` - The first argument is a vector.

The latter case is neater but means we can't vectorize inputs (i.e. get multiple pdfs at the same time), whereas the former allows this but is slightly messier in that each argument must be named

**Comment by fkiraly** [comment]
from a general design perspective, it would make most sense to if arguments of `pdf`, `cdf`, etc, of array distributions are in the same format as the arrays themselves.

That is, for a 2D array of multivariate distributions over the n-variate reals, arguments would be 2D-arrays whose elements are vectors of length n.

This is the only method signature that generalizes to distributions over arbitrary domains, or distribution arrays of arbitrary dimensions.

What is important to distinguish, in my opinion, are dimensions coming from the distribution array, and distributions coming from distributions within being multivariate.

As a compromise, one could add one dimension to the array to cope with real multivariateness.

That is, adopt the convention that the last indices of the argument array are for distribution arguments, while the first indices are for the array dimensions.

For example, in the "covariant type-homogenous array structure" variant:
the `pdf` method of an m x n array of bi-variate normals would take type-homogenous arrays of format m x n whose entries are 2-dimensional vectors.

The `cdf` method of a length m vector of  n x n dimensional matrix-valued distributions (e.g., Wishart) would take type-homogenous vectors of length m whose entries are n x n matrices.


In the "compromise" variant which is perhaps more computationally efficient:
the `pdf` method of an m x n array of bi-variate normals would take numeric arrays of format m x n x 2.

The `cdf` method of a length m vector of  n x n dimensional matrix-valued distributions (e.g., Wishart) would take numeric arrays of format m x n x n.

**Comment by fkiraly** [comment]
Also, this is not really a bug, is it? Just a design inconsistency if seen from a certain perspective.

**Comment by RaphaelS1** [comment]
Struggling to visualise this, I think it would benefit from a whiteboard
