### ISSUE TITLE
pdf bottleneck!

### ISSUE THREAD

**Issue by RaphaelS1** [alan-turing-institute/distr6#61]
Running some tests on efficiency and speed, there's a very clear bottleneck, I suspect in the parent `pdf` method but I found that running:

`Arcsine$new()$pdf(seq.int(0,1,0.001))` 
took 2.19s

And

`dbeta(seq.int(0,1,0.001),0.5,0.5)`
took 0.002s

The former uses the latter internally, which makes me suspect the bottleneck lies in the parent `pdf` that first checks which elements of the vector lie in the support before calling the child `pdf`

**Comment by RaphaelS1** [comment]
Similarly for cdf

**Comment by RaphaelS1** [comment]
Currently the parent classes use `sapply` over vectors which is very inefficient and was only intended as a placeholder anyway. Removing this reduces the time difference to 0.011s and 0.001s respectively.

**Comment by RaphaelS1** [comment]
Finally removing the initial internal checks to see if the vector lies in support, reduces times to 0.008s and 0.001s respectively. Increasing the sequence length to 100,001 makes the time difference marginal. And finally, re-introducing initial support checks on a sequence length of 100,001 sees a 0.01s difference. 

Questions:
1. Clearly use of `sapply` is a poor design choice and vectorising pdf/cdf is preferred but should we also consider use of implementation in C for methods not implemented in R stats?
1. Should we keep using the internal support checks? These are beneficial in that no time is wasted trying to calculate a pdf/cdf that will result in 0/1 because it's outside of support

**Comment by PeterRuckdeschel** [comment]
If I may comment: 

It is generally preferred to write vectorized code right from the beginning, hence to avoid sapply wherever possible. If to this end, you need C methods for specific applications I would consider an implementation, but I would not provide a general wrapper to .Call interfaces to C code, and rather do this in a case by case implementation. 

sapply in fact often is less efficient than hoped for, but still you find tons of code where people for whatever reason have not provided vectorized access to their implemented pdf, cdf. For these cases, if you do not want to re-implement the respective functions from scratch, an sapply wrapper is helpful; it might even pay off to have some generic "vectorize" function for this purpose.

**Comment by RaphaelS1** [comment]
I have removed all the use of `sapply` , I think I implemented it initially for exactly that reason that people have not provided vectorized variants (however I have found I can re-write these myself in many cases). However one case where I have not found a workaround, you may have experience with. If imputing the cdf from the pdf using numerical integration, the formula looks something like `cdf(x) = integrate(pdf, lower = -Inf, upper = x)` but if `x` is a vector then I have found only `sapply` works.

Any suggestions?

**Comment by PeterRuckdeschel** [comment]
True, Raphael, this is what I alluded to in issue #7 point (5) -- in fact for  "D2P" it is not the value of a specified integral you are after but rather the antiderivative as a function. To this end, it pays off to implement a decent, stable numerical quadrature formula like the Simpson method which easily allows for vectorized evaluations.
