### ISSUE TITLE
Analytic/numerical Hypocrisy

### ISSUE THREAD

**Issue by RaphaelS1** [alan-turing-institute/distr6#71]
Several of the recent issues have been about when to use numeric and analytic results. I think we have to be very careful not to be hypocritical and need to take care with documentation. For example, we are drawing the line at estimating infinite sums because of numeric integration, but there are instances of implementing the `gamma` and `factorial` functions in R which both use numerical integration. Now in my opinion, these two functions are fine to use but I want to gauge other's opinion too

**Comment by RaphaelS1** [comment]
Okay specifically with incomplete gamma I haven't found any satisfactory function for incomplete gamma with complex arguments so for this in particular, returning `NULL`, but the argument is still valid for `gamma` and `factorial` (when x < 0)

**Comment by fkiraly** [comment]
Nice issue title :-)

From a very high-level perspective, all R functions (including exp, log etc) are numerical from a principled point of view.
There are alternatives, chiefly used in symbolic and algebraic computation languages or environments, but this is not what R uses.

Where I would draw the line is at whether we have a justifiable guarantee that the result is accurate up to numerical eps.
If we just use an off-shelf integrator, we don't have that, unless we prove some assumptions for inputs and have knowledge of functionality.

If we write a function that computes "infinite sums" in a way that we can prove its accurate up to numerical eps it's fine. For example, when the implementer has provided a formal proof that the remainder term of summation up to the chosen index is smaller than numerical eps.

However, writing code, plus coming up with and writing up a proof, requires substantially more time than just implementing functions we know are numerical eps accurate by looking at them.

A half-way solution is writing code that checks accuracy (by some mathematical principle), e.g., using an iterative remainder term computation via an upper remainder term bound or similar.

So, @RaphaelS1 , indeed the distinction is not as clear as one can naively believe, but there is a more subtle distinction which largely agrees with "can we write this in terms of R-base functions and without numerical integration".

**Comment by fkiraly** [comment]
Would be interested to hear @PeterRuckdeschel 's opinion on this since distr includes some numerical computations...

**Comment by RaphaelS1** [comment]
> Nice issue title :-)

Yes I'm aware of my own hypocrisy, and I've just realised I have an equation for Binomial's entropy which ignores the O(1/n) so now I'm questioning if even that is valid...

> A half-way solution is writing code that checks accuracy (by some mathematical principle), e.g., using an iterative remainder term computation via an upper remainder term bound or similar.

Unfortunately this becomes inefficiency very quickly, we can't check every single calculation.

> So, @RaphaelS1 , indeed the distinction is not as clear as one can naively believe, but there is a more subtle distinction which largely agrees with "can we write this in terms of R-base functions and without numerical integration" (in my opinion).

Although R-base functions often use numerical integration unless we make the assumption that if it's good enough for R-base, and has been around for a long time and is used by everyone, then it should be good enough for us

**Comment by PeterRuckdeschel** [comment]
I have no strong opinion about this. 

Even with a proven accuracy of "eps", like, e.g. a numerical integrator, it may be computationally inefficient, as the example with integrate() shows. In addition, even if computational efficiency is high and accuracy up to "eps" is proven, this accuracy statement comes with additional assumptions on the input usually. Plugging in some input which violates some of these assumptions will often still produce usable, but less accurate results. [in the integrate() example if your integrand fails to be m-times differentiable]. 

So I would judge this from a multi-criterium perspective. 

As to reliability of R base code, I would indeed trust this in general; ("time around" is probably less well a quality indicator than usage ;-) for it is well checked, proven usable, and to a high detail well documented. For code from contributed packages, usually usage is less a criterium, but documentation and checks could serve as criterium.  

Now, once you provide your own numerical tools, I as a user would be happy if they meet these criteria: well documented assumptions and proven accuracy, if possible also with statements as to what is to be expected when input fails to satisfy all assumptions, and some statements as to (a) implementation [R-Code, or compiled code], (b) vectorization (if this is involves many computations, possibly even with a statement on the possibility of parallelization), (c) some example run times. (And at the same time I must confess that probably our code does not meet all these criteria ...)

The example integrator I was suggesting above could easily meet these criteria. Note that integrate() will choose its grid to some extent adaptively -- so accuracy will depend on the upper end-point x of your integral which may not be what you want in case of D2P.

**Comment by fkiraly** [comment]
Just to re-iterate some aspects, and I don't think we disagree: well-used R-base functions - including extremely frequently used functions such as exp, log, etc - are probably fine, though strictly speaking we don't know since there may be no (is there?) documentation as to numerical implementation and accuracy of these.

On the other hand, regarding numerical integration, if we don't know for sure what it's doing - for example it arbitrarily chooses some integration nodes and may miss half of the area - then it may well give unexpected, and problematic/wrong results in cases we didn't anticipate.

For practical reasons, I'd hence add another criterion, (d) complies with unit testing on a sensible range of input-output test cases.
