### ISSUE TITLE
Non-central distributions

### ISSUE THREAD

**Issue by RaphaelS1** [alan-turing-institute/distr6#92]
I've gone back and forth on the 'correct' way to implement the non-central Beta, F and Chi-squared distributions. R stats allows all of these with a `ncp` (non-centrality parameter) and calls the relevant algorithm depending on if `ncp == 0` or `ncp != 0`. However closed form analytic expressions don't exist for several of these and given how decorators currently work, we wouldn't be able to add numeric methods for a non-central Beta, say, if it's implemented as a Beta distribution with a `ncp` parameter. 

Originally I thought that the central and non-central distributions should be the same object with a `ncp` parameter but because of the limitations in analytic expressions I'm now not so sure. Moreover I think the non-central variants are less common in the wild than the common ones and therefore there is a sensible argument to separate them from the central ones. But again I'm not sure... 

Does anyone have a strong opinion on this?

**Comment by fkiraly** [comment]
I think separation makes most sense?

To be honest, I haven't ever used non-central Beta before and wouldn't be able off the top of my head what they are good for (except, apparently, one of many heuristic ways to make Beta more mean-flexible). Beta, on the other hand, are extremely important and widely used.

**Comment by RaphaelS1** [comment]
I was going to suggest the opposite however just thinking about the use-cases, whereas the different forms of the geometric and negative-binomial distributions are all common and can all use the same constructor with a different `form` argument, I am inclined to agree that the non-central distributions are probably not sufficiently popular to merit going in the same distribution (and therefore having to write a lot of annoying conditionals in every method)
